### ISSUE TITLE
No save

### ISSUE THREAD

**Issue by Vlastovka** [Shopkeepers/Shopkeepers#848] opened 2023-10-02 05:24 UTC
If i edit the shop i and open it without shift it cant be traded and if i reopen with shift there no items

**Comment by blablubbabc** [comment] 2023-10-02 09:39
Please let me know your exact server and plugin version. If you are using Paper, make sure that you are using the latest version (v2.17.2) of Shopkeepers.

**Comment by NekaouMike** [comment] 2023-10-04 22:01
Ohhh yes I was about to make a issue about this. In my case here is my "specs"
SK Version: `2.17.1` *Might be patched in v2.17.2 but somehow I didn't get that version
PaperMC ver: `1.20.2`
I'll be back to test 2.17.2

**Comment by NekaouMike** [comment] 2023-10-04 22:01
also now 2.80.0 is out

**Comment by NekaouMike** [comment] 2023-10-04 22:02
OH!
1.17.2 + is NOT uploaded on to bukkit!

**Comment by NekaouMike** [comment] 2023-10-04 22:07
@Vlastovka This is patched in 2.17.2 just so you know I just booted it on my server

**Comment by blablubbabc** [comment] 2023-10-05 06:38
Closing. I assume that this is a duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/842 and therefore fixed in v2.17.2

**Closed by blablubbabc** 2023-10-05 06:38 UTC
Labels: waiting
