### ISSUE TITLE
ShopKeepers TPS DROPS

### ISSUE THREAD

**Issue by AntoLuMeju99** [Shopkeepers/Shopkeepers#557] opened 2019-03-24 14:27 UTC
Shopkeepers version: 2.2.1
Spigot version: PaperSpigot 1.8.8 - R.0.1
Shopkeepers it doing a lot of Scheduler and causing TPS Drops. How i can solve?

https://i.imgur.com/gxhkHJa.png

**Comment by AntoLuMeju99** [comment] 2019-03-24 15:58
Soo?

**Comment by blablubbabc** [comment] 2019-03-24 15:59
Duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/552

This looks like an issue with the server to me. I cannot explain or reproduce those timings. Please try other server versions, without other plugins, ..

**Closed by blablubbabc** 2019-03-24 15:59 UTC
Labels: duplicate
