### ISSUE TITLE
Don`t work trade

### ISSUE THREAD

**Issue by creci** [Shopkeepers/Shopkeepers#640] opened 2020-03-31 09:18 UTC
When trade item with CustomNbtTeg,after restart shopkeepers not see this items in chest.

**Comment by blablubbabc** [comment] 2020-03-31 14:02
Likely an issue with Spigot's item serialization. Can you clarify how you create this item (how I can reproduce this, step by step), what the item's nbt looks like and which Spigot and Shopkeepers versions you are using?

**Comment by blablubbabc** [comment] 2020-06-26 02:13
Closing this as no further information was provided.

**Closed by blablubbabc** 2020-06-26 02:13 UTC
Labels: cannot-reproduce, item-serialization
