### ISSUE TITLE
MythicMobs uncompatible

### ISSUE THREAD

**Issue by Bricec6** [Shopkeepers/Shopkeepers#652] opened 2020-06-17 13:24 UTC
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.9.3`
* **Paper version:** `Paper 350 (1.15.2)`
---

## Reproduction on a fresh and up-to-date Spigot server:

I was **`able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`paper 350`**) with the latest version of Shopkeepers (currently **`<2.9.3>`**), with mythicmobs

## The issue:

Hello, I have a problem with ShopKeepers and MythicsMobs, when I create a shopkeeper, and I introduce custom items from mythicmobs in the shopkeepers, I won't be able to do /mm mobs killal with mythicmobs anymore, and will also tell me that villagers with uuids are not to be found, I teleported there and it was the villagers with the mythicmobs items, the uuids of the villagers seem to change with each reboot.

**Comment by blablubbabc** [comment] 2020-06-17 14:40
> custom items from mythicmobs

This plugin? https://www.spigotmc.org/resources/%E2%9A%94-mythicmobs-free-version-%E2%96%BAthe-1-custom-mob-creator%E2%97%84.5702/

Regarding the actual issue, I am not sure I complete understand. Can you provide all configurations and step by step instructions of what I need to do in order to reproduce this issue? Eg. any relevant non-default MythicMob item and mob configurations, commands I need to execute to setup the shopkeeper, the mm item and mm mobs, commands I need to execute afterwards, what you expect to happen and what you observe to happen instead.

> I won't be able to do /mm mobs killal with mythicmobs anymore

Right away I see no connection between MM's mobs command and Shopkeepers' shops, so I have no idea how one would interfere with the other..

> and will also tell me that villagers with uuids are not to be found

Are the villagers you refer to MM mobs or Shopkeeper mobs? Where do you get this message (console? command output of some MM command?) and what does it say exactly?

>  the uuids of the villagers seem to change with each reboot.

MM villagers or Shopkeeper villagers? Shopkeeper villagers are respawned with every chunk load and unload, so their entity uuids will change. But I don't understand yet how exactly does this affect you or MM's mobs killall command?

**Comment by Bricec6** [comment] 2020-06-17 14:55
yes this plugin, you can come on my server for test it? otherwise it would take too long unless we made a video of it.

**Comment by blablubbabc** [comment] 2020-06-17 16:20
Server ip?

**Comment by Bricec6** [comment] 2020-06-17 17:09
He's local, can we get in touch on discord so we can make an meet to show you?
Brice6#6204

**Comment by blablubbabc** [comment] 2020-06-17 17:22
Consider joining the Shopkeepers discord then: https://discord.gg/d9NKd5z

**Comment by blablubbabc** [comment] 2020-06-25 17:57
Reference to MythicMobs issue ticket: https://www.mythicmobs.net/index.php?threads/bug-mythicmobs-break-shopkeepers.12191/

**Comment by blablubbabc** [comment] 2021-01-01 12:27
Closing this since this seems something for the MythicMobs plugin to fix (error originates from their code, which I am not familiar with).

**Closed by blablubbabc** 2021-01-01 12:27 UTC
Labels: bug, incompatibility, waiting
