### ISSUE TITLE
Can Dupe items 1.18.2

### ISSUE THREAD

**Issue by HanSoloSnipe** [Shopkeepers/Shopkeepers#883] opened 2024-05-16 12:20 UTC
## Preliminaries:

* **Shopkeepers version:** `last`
* **Spigot version:** `1.18.2`
---

* I have checked that my issue/question does not get answered by: Yes
 

By using Shopkeeper editor, can dupe items. 

- Open editor
- Take item in hand
- Place in inventory (by clicking some time, it will be placed in inventory)

That's work with menu buttons, and selling items

**Comment by blablubbabc** [comment] 2024-05-16 16:53
Being able to pick up items from the shopkeeper menus is usually caused by an incompatibility with one of your other plugins. Please try to reproduce your issues without other plugins. Also try to reproduce it on the latest Spigot server version. And check the "Known issues" wiki page if you are using any of the plugins listed there: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues

**Comment by blablubbabc** [comment] 2024-06-18 14:43
Closing this as no further information was provided on how to reproduce this issue.

**Closed by blablubbabc** 2024-06-18 14:43 UTC
Labels: cannot-reproduce
