### ISSUE TITLE
Crash all time by shopkeepers

### ISSUE THREAD

**Issue by FyFou57** [Shopkeepers/Shopkeepers#520] opened 2018-08-28 16:05 UTC
* Try to reproduce your issue when using: Dont know
 1.8.8 Paperspigot (shopkeepers 2.2.1)
  * No other plugins.
  * No kinds of other server or client mods.

We are sur 100% it's shopkeepers the reason of crash server : https://pastebin.com/Udy5J5Jz 
all day, the server crash 1/2times, dont know why. 
We use shopkeepers recently, and since we have crashes however we can not do without the plugin, please, make a fix as soon as possible it is totally unusable if it crash :(
We use it only for admin shop, no mod.

**Comment by blablubbabc** [comment] 2018-08-28 16:37
I don't see how that crash is pointing to shopkeepers. Can you post the full crash report?

**Comment by FyFou57** [comment] 2018-08-28 16:59
The tests have already been done, I have several servers, their only common point and to have shopkeepers, one of the two had no problem to crash up to add shopkeepers

As for the crash, actually, as you see it does not mean anything I have been doing servers for a long time I have never seen this kind of error.

Can you add me discord ? or give me your discord ?

**Comment by blablubbabc** [comment] 2018-08-28 17:42
You can chat with me on irc (blablubbabc on spigot's irc server, or EsperNet). But still, I don't see yet how I would be able to help you.. right now it points to some issue with Minecraft, Spigot or PaperSpigot. That's why I suggested that you try some different server versions / builds (for example the latest Spigot that supports 1.8.8), and see if that resolves the issue.

**Comment by FyFou57** [comment] 2018-08-28 17:45
One of the servers where there is the problem and in 1.7 and the other 1.8. Maybe shopkeepers have problems with paperspigot?

**Comment by blablubbabc** [comment] 2018-08-28 17:48
> Maybe shopkeepers have problems with paperspigot?
I am not aware of any at the moment. And if there were, this would be something for the PaperSpigot team to fix. But to find out whether the issue is specific to PaperSpigot, you will have to try reproducing the issue with Spigot.

**Comment by FyFou57** [comment] 2018-08-28 18:04
I do not know if the problem comes from paperspigot, it's possible ... In any case on one of the servers, shopkeepers and delete since the beginning of aprème and still no crash (before there was often a crash to 18h) Can not solve the problem?

**Comment by blablubbabc** [comment] 2018-08-28 18:33
As of right now it's impossible to say what is causing this.. and therefore impossible to do anything about it.
 My recommendation is:
* Try it with Spigot. Try it with different versions / builds.
* If the crashing persists there: Gather a bunch of those crash reports and compare them (do they always crash at the same point, is there a common pattern to what initiates the crash (what happens right before the crash), etc.).

In any case, there is nothing I can do on Shopkeepers' side as of right now, so I will close this ticket as 'declined'. If the issue should persist even when running Spigot, and you have some information that points to something more specifically related to Shopkeepers, then let me know and I will look into this again.

**Closed by blablubbabc** 2018-08-28 18:33 UTC
