### ISSUE TITLE
Failed to load shopkeeper 'x': Shopkeeper data migration failed!

### ISSUE THREAD

**Issue by galuxosi** [Shopkeepers/Shopkeepers#843] opened 2023-09-17 08:09 UTC
## Preliminaries:

* **Shopkeepers version:** `2.17.1`
* **Spigot version:** `This server is running Paper version git-Paper-193 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 581b683)
You are running the latest version
Previous version: git-Paper-183 (MC: 1.20.1)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help to reproduce the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* ... Anything else that might be useful to reproduce and identify the issue.

I joined my server and I noticed that all my shopkeepers were dissapered, and when I wanted to create a new shopkeepers they don't save their products. I viewed logs and saw that all of my shopkeepers weren't loaded with error: "Failed to load shopkeeper 'X': Shopkeeper data migration failed!" 
Logs: https://mclo.gs/HbJSfBH
I didn't change the config except debuging(I enabled it after finding this bug)

**Comment by Draghonir** [comment] 2023-09-17 09:45
same issue

**Comment by blablubbabc** [comment] 2023-09-17 14:35
Duplicate of #842

**Closed by blablubbabc** 2023-09-17 14:35 UTC
