### ISSUE TITLE
Bug: Item got italic

### ISSUE THREAD

**Issue by JaHollYT** [Shopkeepers/Shopkeepers#664] opened 2020-07-06 05:58 UTC
Sry, i hate these pre Lines...

Shopkeeper Version 2.10.0 & Paper 1.15.2 -- git-Paper-333

I got a money Note(it's a renamed stick with NBT-Data). The Title of that item is "Geldschein" with italic false.
When I put it into a Shopkeeper as a payment item it works. But after a reload of shopkeepers / restart of the server the item title got italic, so you can't pay with the Moneynote anymore.

Item:
/give @p stick{itemsadder:{id:"banknote",namespace:"itemsadder"},display:{Name:"[{\"text\":\"Geldschein\",\"italic\":false}]",Lore:["[{\"text\":\"Wert 1 Holly\",\"italic\":false,\"color\":\"white\"}]"]},CustomModelData:20001} 1

**Comment by blablubbabc** [comment] 2020-07-06 11:58
I am copying my reply I gave someone else with this issue here:

Shopkeepers uses a piece of API from Spigot to save and load items to/from the save.yml file.
Unfortunately Spigot's item serialization API is currently not able to exactly reproduce the original NBT data in various cases. You most likely run into this issue if you are using items with custom display names or lore. Spigot saves those as plain text with legacy formatting codes into the save.yml. When loading these items again it has to convert this plain text representation back to Minecraft's json text component representation. It is likely that the internal text representation produced by Spigot does not match your original text representation.

On top of this underlying issues, Spigot also has made some changes to the text format they produce during the update for MC 1.16. So items which have worked fine previously may be broken now.

Relevant issue tickets are:
* https://hub.spigotmc.org/jira/browse/SPIGOT-5063
* https://github.com/Shopkeepers/Shopkeepers/issues/662
* https://github.com/Shopkeepers/Shopkeepers/issues/578

Possible solutions to this issue are:
* Spigot fixing the underlying issues of not persisting the item's exact nbt data during item deserialization.
* Avoid using Minecraft mechanisms for creating the items / avoid specifying the exact nbt data of the items, and instead use a plugin which uses Spigot's API to create the items.
* Stick to the internal data format Spigot uses when a plugin would create the same items. I.e. update your commands / plugin setups / configurations to produce items with nbt data which matches the nbt data format produced by Spigot.

Reimplementing the item serialization of Spigot is out of scope for me to do as part of a plugin. I may be able to look into fixing this issue inside of Spigot and creating a PR for this at some point, but I have no time do that currently (or any time soon).

Instead I have created a snapshot which includes some tools which might be helpful to deal with this issue: https://nexus.lichtspiele.org/repos...SHOT/Shopkeepers-2.10.1-20200704.035816-5.jar
The complete changelog can be found here: https://github.com/Shopkeepers/Shopkeepers/blob/master/CHANGELOG.md
Among other things, this snapshot includes the following tools:
* A `/shopkeeper givecurrency [player] ['low'|'high'] [amount]` command which lets you produce the currency items specified inside the config in Spigot's data format.
* A `/shopkeeper convertItems [player] ['all']` command which lets you convert the held, or all items inside the inventory, to conform to Spigot's data format.
* A config option `convert-player-items` to automatically convert items inside player inventories and shop chests whenever someone interacts with a shopkeeper. However, this setting comes with a performance hit, so either try to avoid using it or only use it as long as you suspect your players to still have items in the old format.

Another useful tool is Minecraft's built in `/data get ..` command for inspecting the internal nbt data of items.

**Comment by blablubbabc** [comment] 2020-07-06 11:59
Closing this as 'duplicate' because I consolidate all issues related to items changing their internal data format during de/serialization in this ticket https://github.com/Shopkeepers/Shopkeepers/issues/578

**Closed by blablubbabc** 2020-07-06 11:59 UTC
