### ISSUE TITLE
issue with trades

### ISSUE THREAD

**Issue by SnakeAmazing** [Shopkeepers/Shopkeepers#653] opened 2020-06-18 13:40 UTC
## Preliminaries:

* **Shopkeepers version:** `<2.2.4>`
* **Spigot version:** `This server is running CraftBukkit version git-PaperSpigot-"4c7641d" (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

Hello, my problem is with trades. It has been workin fine for a long time but yesterday I realized that when my users try to trade for the second item in the shop, the item is converted to the first one. I tryed updating the plugin, removing configuration, and nothing changed.

**Comment by blablubbabc** [comment] 2020-06-18 14:07
> when my users try to trade for the second item in the shop, the item is converted to the first one

Can you make a concrete example, maybe explain with a screenshot.

**Comment by SnakeAmazing** [comment] 2020-06-18 14:11
![2020-06-18_16 08 58](https://user-images.githubusercontent.com/53049922/85030762-23a17180-b17e-11ea-93e7-31a9508a748a.png)
![2020-06-18_16 09 07](https://user-images.githubusercontent.com/53049922/85030770-24d29e80-b17e-11ea-9ee8-9a261045c109.png)
![2020-06-18_16 09 09](https://user-images.githubusercontent.com/53049922/85030774-2603cb80-b17e-11ea-9709-eab9551b15fb.png)

On the first screenshot you can see that i'm buying the pickaxe, and in the second you can see that I'm buying the sword, but when I click the sword it turns into the pickaxe set in the first place. Sorry for my english I'm not native. I wish you can understandme.

**Comment by blablubbabc** [comment] 2020-06-18 14:18
I just tried to reproduce this but I am not able to. http://prntscr.com/t24b3j
I am using Spigot git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) and Shopkeepers v2.2.4

Can you try to reproduce this on a fresh and up-to-date Spigot 1.8.8 without other plugins? Also make sure that your minecraft client is up-to-date and that you are not using any client mods.

**Comment by SnakeAmazing** [comment] 2020-06-18 14:22
Yes, doing that it worked. I don't know what is causing that issue.

**Comment by blablubbabc** [comment] 2020-06-18 14:23
What worked? Removing other plugins? Using Spigot?

**Comment by SnakeAmazing** [comment] 2020-06-18 14:24
using a fresh paper spigot 1.8.8 and only using shopkeepers

**Comment by blablubbabc** [comment] 2020-06-18 14:28
Okay, so then try to readd your plugins and see if it still works. If yes, then the issue is somehow related to PaperSpigot. If there is a newer version of PaperSPigot for MC 1.8.8, try that then. In either case, I won't be able to help with Paper specific issues. That's up to them to resolve, but I guess they no longer provide support for MC 1.8 either.

If the issue reappears once you add your other plugins back, then the issue is caused by some of those plugins. You will then need to track down which plugin is causing this. My guess would be some plugin which involves hooking into the server-client connection (eg. ViaVersion, or similar plugins, in case you use those), since the issue seems to be that the client believes that it has selected a different trade to the one selected on the server.

**Comment by SnakeAmazing** [comment] 2020-06-18 14:31
Okay, I"ll try that, later I'll send you a response. Thanks for help!

**Comment by SnakeAmazing** [comment] 2020-06-19 09:34
Ok, I've tryed some things and apperently the issue is with the trades that gives you tools (swords, pickaxes, etc) because I've tryed setting up a shopkeeper trading regular objects (wool, doors, redstone, etc) and it worked perfectly. I don't know why is doing that.

**Comment by blablubbabc** [comment] 2020-06-19 12:49
Since this issue disappeared once you started using no other plugins and Spigot, you need to figure out whether this is a Paper issue or caused by some other plugin on your server. If it only involves specific items, my guess is that there might be some plugin involved (but that is just a guess).

**Comment by SnakeAmazing** [comment] 2020-06-19 13:54
The problem isn't related with paper, because I have tryed the plugin in a fresh paper server too, so yes probbably is another plugin involved. Right now I have solved the issue creating a specific shopkeeper for each trade so that worked for me, but I'll continue searching the plugin that causes that. Thanks for all the help!!

**Comment by blablubbabc** [comment] 2020-06-19 13:59
Okay, I will close this ticket assuming that this is caused by another plugin. But if you figure out which other plugin is involved, let me know so that this incompatibility can either be resolved or I can at least mention it inside the wiki in case someone else runs into this same issue.

**Closed by blablubbabc** 2020-06-19 13:59 UTC
Labels: bug

**Comment by blablubbabc** [comment] 2020-06-20 13:57
@SnakeAmazing Could you post your plugins list? Someone else might experience the same issue (not with tool items though). His plugins are: https://cdn.discordapp.com/attachments/606332085308751892/723897747672924220/bandicam_1315.jpg
Are you also using any of those?
