### ISSUE TITLE
1.18 bug

### ISSUE THREAD

**Issue by soupcoup** [Shopkeepers/Shopkeepers#769] opened 2021-12-08 13:50 UTC
dont remember how but i got the 1.18 snapshot and it was working until it randomly stopped and now whenever i do /shopkeeper i get this error in the console

[05:48:14 INFO]: partyplayz issued server command: /shopkeeper
[05:48:14 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.14.0-SNAPSHOT+02f69430 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2267) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2078) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2059) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.jar:git-Paper-59]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-59]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by blablubbabc** [comment] 2021-12-08 14:31
The error mentions that the plugin is disabled. Can you please restart the server and try the command again? If the plugin is not able to enable during server startup, then please send the server log of your server startup.
If the plugin suddenly disabled while the server was running, you will need to go through your server log and see when it got disabled and whether it mentions there why it got disabled.

**Comment by soupcoup** [comment] 2021-12-08 16:32
i figured out what caused it, when adding the 1.18 version of world guard the villagers are removed and i get the error https://builds.enginehub.org/job/worldguard/19088

**Comment by blablubbabc** [comment] 2021-12-18 05:21
My guess is that you probably had some other error earlier in your log, which caused the Shopkeepers plugin to either disable, or fail to enable. Maybe that other error was caused by some buggy or incompatible WorldGuard snapshot. But without further information (e.g. the complete log) I can only speculate.

However, I just briefly tested the latest WorldEdit and WorldGuard snapshots together with the latest Shopkeepers version, and I am not able to reproduce any issue. So if the issue was caused by some older WorldGuard snapshot version, maybe this issue has already been resolved by now.

I also assume that you already resolved the issue in your case by now anyway, so I will close this ticket.

**Closed by blablubbabc** 2021-12-18 05:21 UTC
Labels: waiting

**Comment by soupcoup** [comment] 2021-12-25 17:07
if i restart the server multiple times with the snapshot version of world guard it is a coin flip on weather or not the villagers will be there, they often don't spawn in and i need to restart my server multiple times but its not awfull
