### ISSUE TITLE
Can`t edit shopkeepers

### ISSUE THREAD

**Issue by Bedroczek** [Shopkeepers/Shopkeepers#861] opened 2023-12-10 12:26 UTC
I have problem with shopkeepers beacuse i can`t edit them, anyone know what caused that?

**Comment by blablubbabc** [comment] 2023-12-10 12:30
Turn on debug mode (`/shopkeeper debug`) and check the server log output when you interact with a shopkeeper entity. Maybe this spits out some useful information.

**Comment by PetyXbron** [comment] 2023-12-25 11:05
Hi, one player reported me, that he cannot move with his Shopkeeper. It officially moves as chat says, but graphically it isn't there. I don't really understand your debug system, but this should be the log:
```
[11:57:33 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) at VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-35.593075,yaw=-188.90552}
[11:57:33 INFO]: [Shopkeepers]   Cancelling entity interaction
[11:57:33 INFO]: [Shopkeepers]   Ignoring InteractAtEntity event
[11:57:33 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-35.593075,yaw=-188.90552}
[11:57:33 INFO]: [Shopkeepers]   Cancelling entity interaction
[11:57:33 INFO]: [Shopkeepers] UI session 'trading' started for player Pohodovej_rybar.
[11:57:33 INFO]: [Shopkeepers] Opening UI 'trading' ...
[11:57:34 INFO]: [Shopkeepers] Inventory event (InventoryCloseEvent): player=Pohodovej_rybar, view-type=MERCHANT, view-title=§2Kupec
[11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar closed UI 'trading'.
[11:57:34 INFO]: [Shopkeepers] UI session 'trading' ended for player Pohodovej_rybar.
[11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) at VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-26.96174,yaw=-189.5741}
[11:57:34 INFO]: [Shopkeepers]   Cancelling entity interaction
[11:57:34 INFO]: [Shopkeepers]   Ignoring InteractAtEntity event
[11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-26.96174,yaw=-189.5741}
[11:57:34 INFO]: [Shopkeepers]   Cancelling entity interaction
[11:57:34 INFO]: [Shopkeepers] UI session 'editor' started for player Pohodovej_rybar.
[11:57:34 INFO]: [Shopkeepers] Opening UI 'editor' ...
[11:57:35 INFO]: [Shopkeepers] Inventory click: player=Pohodovej_rybar, view-type=CHEST, view-title=Editor kupce, raw-slot-id=37, slot-id=37, slot-type=CONTAINER, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PICKUP_ALL, time: 62946626513
[11:57:35 INFO]: [Shopkeepers] Ignoring inventory event of Pohodovej_rybar: The UI has been deactivated and is probably about to get closed.
[11:57:35 INFO]: [Shopkeepers] Player Pohodovej_rybar closed UI 'editor'.
[11:57:35 INFO]: [Shopkeepers] UI session 'editor' ended for player Pohodovej_rybar.
[11:57:35 INFO]: [Shopkeepers] Shopkeeper 621: No offers have changed.
[11:57:36 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with block at lands,-10,-1,32
[11:57:36 INFO]: [Shopkeepers]   Non-shopkeeper
[11:57:36 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (OFF_HAND) with block at lands,-10,-1,32
[11:57:36 INFO]: [Shopkeepers]   Non-shopkeeper
[11:57:36 INFO]: [Shopkeepers] Saved shopkeeper data (1 dirty, 0 deleted): 64 ms (Async execution delay: 38 ms, Async execution: 25 ms)```
Also, we have recorded a video for you. Unfortunately, plugin's strings are already translated, but I think you will handle it :)
Here is it: https://www.veed.io/view/1ef8d9dc-93cd-474d-9e55-a8778d033984

**Comment by PetyXbron** [comment] 2023-12-25 11:08
Update: it seems, that after a restart of the server, the Shopkeeper moves.

**Comment by blablubbabc** [comment] 2023-12-25 11:21
> Hi @blablubbabc, one player reported that he **cannot move with his Shopkeeper**. It officially moves as the chat says, but it isn't there graphically.
> 
> We have recorded a video for you. Unfortunately, the plugin's strings are already translated, but I think you will handle it :) Here is it: https://www.veed.io/view/1ef8d9dc-93cd-474d-9e55-a8778d033984
> 
> Also, I don't understand your debug system, but this should be the log:
> 
> ```
> [11:57:33 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) at VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-35.593075,yaw=-188.90552}
> [11:57:33 INFO]: [Shopkeepers]   Cancelling entity interaction
> [11:57:33 INFO]: [Shopkeepers]   Ignoring InteractAtEntity event
> [11:57:33 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-35.593075,yaw=-188.90552}
> [11:57:33 INFO]: [Shopkeepers]   Cancelling entity interaction
> [11:57:33 INFO]: [Shopkeepers] UI session 'trading' started for player Pohodovej_rybar.
> [11:57:33 INFO]: [Shopkeepers] Opening UI 'trading' ...
> [11:57:34 INFO]: [Shopkeepers] Inventory event (InventoryCloseEvent): player=Pohodovej_rybar, view-type=MERCHANT, view-title=§2Kupec
> [11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar closed UI 'trading'.
> [11:57:34 INFO]: [Shopkeepers] UI session 'trading' ended for player Pohodovej_rybar.
> [11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) at VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-26.96174,yaw=-189.5741}
> [11:57:34 INFO]: [Shopkeepers]   Cancelling entity interaction
> [11:57:34 INFO]: [Shopkeepers]   Ignoring InteractAtEntity event
> [11:57:34 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with VILLAGER at Location{world=CraftWorld{name=lands},x=-6.5,y=0.0,z=31.5,pitch=-26.96174,yaw=-189.5741}
> [11:57:34 INFO]: [Shopkeepers]   Cancelling entity interaction
> [11:57:34 INFO]: [Shopkeepers] UI session 'editor' started for player Pohodovej_rybar.
> [11:57:34 INFO]: [Shopkeepers] Opening UI 'editor' ...
> [11:57:35 INFO]: [Shopkeepers] Inventory click: player=Pohodovej_rybar, view-type=CHEST, view-title=Editor kupce, raw-slot-id=37, slot-id=37, slot-type=CONTAINER, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PICKUP_ALL, time: 62946626513
> [11:57:35 INFO]: [Shopkeepers] Ignoring inventory event of Pohodovej_rybar: The UI has been deactivated and is probably about to get closed.
> [11:57:35 INFO]: [Shopkeepers] Player Pohodovej_rybar closed UI 'editor'.
> [11:57:35 INFO]: [Shopkeepers] UI session 'editor' ended for player Pohodovej_rybar.
> [11:57:35 INFO]: [Shopkeepers] Shopkeeper 621: No offers have changed.
> [11:57:36 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (HAND) with block at lands,-10,-1,32
> [11:57:36 INFO]: [Shopkeepers]   Non-shopkeeper
> [11:57:36 INFO]: [Shopkeepers] Player Pohodovej_rybar is interacting (OFF_HAND) with block at lands,-10,-1,32
> [11:57:36 INFO]: [Shopkeepers]   Non-shopkeeper
> [11:57:36 INFO]: [Shopkeepers] Saved shopkeeper data (1 dirty, 0 deleted): 64 ms (Async execution delay: 38 ms, Async execution: 25 ms)```
> ```

Consider creating a separate ticket for your issues in the future.
Anyway, regarding your issue: This is a known issue on recent versions of the Paper server: Paper made some change to how they call entity teleport events, and now the plugin detects and cancels its own entity teleporting. The next update will include a fix.

**Comment by blablubbabc** [comment] 2023-12-25 11:22
Closing this ticket since no further information was provided that could help reproduce the issue.

**Closed by blablubbabc** 2023-12-25 11:22 UTC
Labels: cannot-reproduce
