### ISSUE TITLE
Renting payment issue

### ISSUE THREAD

**Issue by melinstagibson** [Shopkeepers/Shopkeepers#493] opened 2018-02-20 18:05 UTC
I have a server where people can rent a certain amount of shopkeepers in a marketplace.

The problem is that if someone reached his shopkeeper limit as assigned via permissions the rentable shopkeepers will still take the payment and then tell the user he cant buy more but the payment will still be lost.

**Comment by blablubbabc** [comment] 2018-02-20 20:16
Was able to reproduce: This occurs if the player has more items than would be required: The stack of items gets reduced then. Caused by this line of code: https://github.com/Shopkeepers/Shopkeepers/blob/master/src/main/java/com/nisovin/shopkeepers/shoptypes/PlayerShopkeeper.java#L295

I will fix this in the next update.

**Comment by melinstagibson** [comment] 2018-04-17 13:44
sweet, any eta for an update?

**Comment by blablubbabc** [comment] 2018-05-18 02:55
Should be fixed in v1.87. Please let me know if that is the case.

**Closed by blablubbabc** 2018-05-18 02:55 UTC
Labels: accepted, bug, verified
