### ISSUE TITLE
Found a warn/error when trying to use /shopkeepers admin npc

### ISSUE THREAD

**Issue by axemwa** [Shopkeepers/Shopkeepers#548] opened 2019-02-10 13:53 UTC
Shopkeepers 2.4.1
Paper Spigot - 1.13.2 - 521

https://pastebin.com/Yx7x1cSn

**Comment by blablubbabc** [comment] 2019-02-10 14:10
Seems to be Citizens related. Can you create a citizens npc (with the citizens command), or is this failing as well?

**Comment by axemwa** [comment] 2019-02-10 14:18
I can still make citizens as normal, 
using this build of citizens [00:46:49 INFO]: Version: 2.0.24-SNAPSHOT (build 1616)

http://ci.citizensnpcs.co/job/Citizens2/

**Comment by blablubbabc** [comment] 2019-02-10 15:57
I just tried and cannot reproduce the issue on a freshly setup server..

**Comment by axemwa** [comment] 2019-02-10 17:42
The steps I take to reproduce are, while the server was on I changed "enable-citizen-shops: false" to "enable-citizen-shops: true" in the config, then saved it then did "/shopkeepers reload", then I did /shopkeepers admin npc then the WARN came up. So maybe the reload caused it?

Im using Paper Spigot 1.13.2 - Build 521
https://papermc.io/ci/job/Paper-1.13/

**Comment by blablubbabc** [comment] 2019-02-10 17:47
I did the exact same steps (reload, same paper version). So the issue has to be something else, specific to your server/setup (other plugins, server configs, plugin configs, previous errors, ..)

**Comment by axemwa** [comment] 2019-02-10 17:50
ok ill further investigate

**Comment by axemwa** [comment] 2019-02-10 17:51
oh also this was all happening inside a WorldGuard region, that was the other condition

**Comment by blablubbabc** [comment] 2019-02-10 18:04
Here was someone with the same error. Like said in that ticket: Can you try without other plugins?

**Comment by axemwa** [comment] 2019-02-10 18:12
Yeah I'll further investigate and I'll try without other plugins

**Comment by blablubbabc** [comment] 2019-02-16 01:35
Closing this, as this doesn't seem to be an issue with Shopkeepers.

**Closed** 2019-02-16 01:35 UTC
Labels: bug, cannot-reproduce, incompatibility
