### ISSUE TITLE
Plugin stoped working after reload/server restart.

### ISSUE THREAD

**Issue by TwanMuc** [Shopkeepers/Shopkeepers#898] opened 2024-07-10 20:01 UTC
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.22.1.jar`
* **Spigot version:** `This server is running Paper version 1.20.6-DEV-ver/1.20.6@20f5165 (2024-07-02T22:01:17Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
You are running the latest version`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **` Paper version 1.20.6-DEV-ver/1.20.6@20f5165 (2024-07-02T22:01:17Z)`**) with the latest version of Shopkeepers (currently **`Shopkeepers-2.22.1.jar`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

The problem I have is that I have spent some time making certain shopkeepers with items (such as written books and objects with special names etc.)  but after I did a reload, All the shopkeepers are gone, and the only thing I can do is delete the shopkeeper folder and reload the server, but I have lost all my progress, and when I put the save.yml back into the shopkeeper data folder that I made as a backup, the plugin immediately stops working, with the /pl command, it also turned red, and in the console, a whole text appears:

10.07 21:45:02 [Server] [ERROR] Command exception: /shopkeeper
10.07 21:45:02 [Server] [INFO] org.bukkit.command.CommandException: Cannot execute command 'shopkeeper' in plugin Shopkeepers v2.22.1 - plugin is disabled.
10.07 21:45:02 [Server] [INFO] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
10.07 21:45:02 [Server] [INFO] at io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:91) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.execution.CommandQueueEntry.action(CommandQueueEntry.java:5) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:448) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:355) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:342) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.commands.Commands.performCommand(Commands.java:337) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:2202) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2176) ~[?:?]
10.07 21:45:02 [Server] [INFO] at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:02 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[?:?]
10.07 21:45:03 [Server] [INFO] at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1511) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:195) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[?:?]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1488) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[?:?]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1377) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1238) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-DEV-20f5165]
10.07 21:45:03 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

Could this possibly be caused by one of the other plugins I'm using on the server or is it related to the plugin itself? I've tested it on both Spigot 1.20.6 and now on Paper 1.20.6

The plugins I use:
 - Citizens, dynmap, ElderGuardianBoss, EntityScaler, Essentials, GroupManager, Jumpscares, *Lores, MyDog, Not-Too-Expensive Sentinel, Shopkeepers, Vault, WorldEdit, WorldGuard, WorldGuardExtraFlags

**Comment by blablubbabc** [comment] 2024-07-10 22:09
Please check your server log for errors immediately after (re-)loading the plugin. Your posted error only mentions that the plugin is disabled, but gives no indication why it failed to enable.

My guess is that maybe the plugin fails to load your save data (there are some item serialization issues in Spigot 1.20.6 that were not yet fixed in the server, afecting certain items).

But without a complete log of the plugin's startup I cannot tell for sure what the issue is.

**Comment by blablubbabc** [comment] 2024-07-30 20:16
Closed as no further information was provided.

**Closed by blablubbabc** 2024-07-30 20:16 UTC
Labels: waiting
