### ISSUE TITLE
ShopKeepers - TPS Drops

### ISSUE THREAD

**Issue by AntoLuMeju99** [Shopkeepers/Shopkeepers#552] opened 2019-03-10 15:11 UTC
* **Shopkeepers version:** `2.2.1`
* **Spigot version:** `PaperSpigot 1.8.8 - R.0.1`
---

Shopkeepers it doing a lot of Scheduler and causing TPS Drops. How i can solve?

https://i.imgur.com/d1hJBtt.png

**Comment by blablubbabc** [comment] 2019-03-10 15:18
I cannot explain how you get those timings. So please try to reproduce your issue on an up-to-date Spigot server and without other plugins.

**Comment by AntoLuMeju99** [comment] 2019-03-10 15:19
What u mean on an up-to-date Spigot? My server need to be 1.8.8 or other plugins wont work

**Comment by blablubbabc** [comment] 2019-03-10 15:45
Try it without other plugins. A quickly setup local server should suffice for testing this.

**Comment by blablubbabc** [comment] 2019-03-10 15:59
This is the code that gets triggered on PlayerItemHeldEvent: https://github.com/Shopkeepers/Shopkeepers/blob/master/src/main/java/com/nisovin/shopkeepers/shopcreation/CreateListener.java#L46
There is nothing performance heavy there and I cannot reproduce your timings myself.
So my guess would be that this was either a one-time thing, or its an issue/interference with your server version or other plugins.
That why I suggest you to try out other setups (other server versions, other plugins), to hopefully track down the specifics of your setup that cause this.

If you are able to consistently reproduce this with some minimal setup (specific server version or interfering plugin), then I can look into how to potentially solve this. Though, if its related to your server version and not an issue on newer versions then there is nothing on my end to do about it.

**Comment by blablubbabc** [comment] 2019-03-17 15:20
Closing this as there is nothing I can do with the provided information. I am not able to reproduce these timings. A full timings report of the server might be useful, as well as feedback regarding testing without plugins and testing with different server versions.

**Comment by AntoLuMeju99** [comment] 2019-03-24 16:00
I did, without plugins no problem

**Comment by blablubbabc** [comment] 2019-03-24 16:02
Try with only Shopkeepers. If the issue occurs, let me know which exact server build you are using, so that I can try to reproduce the issue.

**Comment by AntoLuMeju99** [comment] 2019-03-24 16:05
All server lag. 

server build: https://i.imgur.com/covFnb3.png

**Comment by blablubbabc** [comment] 2019-03-24 16:18
PaperSpigot is no longer available for 1.8.8. I am trying to reproduce this with Spigot 1.8.8 now. Please try to reporudce this with Spigot 1.8.8 as well. (Run BuildTools with --rev 1.8.8 option)

**Comment by blablubbabc** [comment] 2019-03-24 16:37
Cannot reproduce the lag: https://timings.aikar.co/?id=0e9452a93ade47dba26c8c3674f528d1#timings

**Comment by AntoLuMeju99** [comment] 2019-03-28 17:12
I cant. What it can be?

https://i.imgur.com/xuwzwOY.png

**Comment by blablubbabc** [comment] 2019-03-28 22:12
> Can you send me a full timings report?

**Closed** 2019-04-04 05:28 UTC
Labels: cannot-reproduce, performance, waiting

**Comment by blablubbabc** [comment] 2019-04-04 05:29
If you have further information on how to reproduce this on a fresh server, let me know and I will look into it again.

**Comment by AntoLuMeju99** [comment] 2019-04-04 19:32
On a fresh server with only Shopkeeper no tps drops :(

What it can be? It's a Prison

https://i.imgur.com/JmYXY7h.png

**Comment by blablubbabc** [comment] 2019-04-04 23:26
Then maybe some other plugin is interfering. Can you provide a (minimal) list of plugins this can be reproduced with? Are yiu using any 'analytical' plugins which might be hooking into other plugin's listeners?
