### ISSUE TITLE
Shopkeepers update for MC 1.14

### ISSUE THREAD

**Issue by hurrgurl** [Shopkeepers/Shopkeepers#562] opened 2019-04-30 00:49 UTC
CraftBukkit version git-Spigot-4d24e36-5193f76 (MC: 1.14) (Implementing A
PI version 1.14-R0.1-SNAPSHOT)                            

If disable-gravity=true sometimes Shopkeepers don't turn heads when player is near them.

Not quite sure why it only affects some Shopkeepers but not the others.

_P.S.
What does this do?
gravity-chunk-range: 4_

**Comment by MonstahGames** [comment] 2019-04-30 16:58
Looking forward to the working release!

**Comment by hurrgurl** [comment] 2019-05-08 00:49
git-Paper-7 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)                                                         

All Shopkeepers converted to 1.14 from 1.13.2 just fine. Small issues with lore/text formatting on items, but that's to be expected.

disable-gravity=true
Doesn't keep Shopkeepers in the air for me, they fall down. Can you reproduce?

Besides that all Shopkeepers function just as expected. Some also turn heads, who knows why. :)

Doing plugin reload or disconnect/reconnect while near shopkeepers makes them notice you.

**Comment by blablubbabc** [comment] 2019-05-08 14:44
> Small issues with lore/text formatting on items, but that's to be expected.

Can you provide me an example for lore that does not get properly imported on Spigot 1.14? This sounds like something that would need to be fixed in Spigot's item deserialization.

Regarding Shopkeepers for MC 1.14: I am waiting for Spigot to fix some chunk loading related issue (https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/549/). This is planned for after the update to MC 1.14.1.

I will not look into issues regarding running Shopkeepers on MC 1.14 until after I have released an official update.

**Comment by blablubbabc** [comment] 2019-05-08 23:04
For anyone interested in experimenting, I have uploaded a snapshot build for MC 1.14:
http://nexus3.cube-nation.de/repository/snapshots/com/nisovin/shopkeepers/Shopkeepers/2.7.0-SNAPSHOT/Shopkeepers-2.7.0-20190508.225429-1.jar

Due to the above mentioned chunk / entity issue, it is not recommended to use this on a production server yet. Also, depending on the changes that will still be made until an official release, it might not be possible to safely migrate from this snapshot version to the final version for MC 1.14.x. So make sure to **backup your 1.13.x Shopkeepers data** and use this later for the official update to MC 1.14 (instead of using the data created while running this snapshot version)!

**Comment by hurrgurl** [comment] 2019-05-15 20:22
> Can you provide me an example for lore that does not get properly imported on Spigot 1.14? This sounds like something that would need to be fixed in Spigot's item deserialization.

https://proxy.spigotmc.org/5fcaf952dfdfaead0430a3dee2aba4a023644919?url=https%3A%2F%2Fi.imgur.com%2Fju6DLID.png

**Comment by blablubbabc** [comment] 2019-05-15 20:57
Item lore might be fixed with the latest update of Spigot: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f69095731175a8d77f6c6f973721fa9a7182ff5d

**Comment by successed** [comment] 2019-05-28 22:41
items can be taken over during the exchange. the dupe in here.

**Comment by hurrgurl** [comment] 2019-05-28 22:43
> items can be taken over during the exchange. the dupe in here.

Can you be more specific and provide steps to reproduce this dupe?

**Comment by blablubbabc** [comment] 2019-05-28 23:15
v2.7.0 has been released which provides support for Spigot 1.14.2.

If you run into any issues, or issues mentioned here are not resolved by that version yet, then please create new tickets for these issues and provide detailed information on how to reproduce them. Also make sure that you reproduce them on a fresh and up-to-date Spigot server, in order to ensure that those issues are not related to running an incompatible or snapshot build previously.

**Closed by blablubbabc** 2019-05-28 23:15 UTC
Labels: fixed, outdated-plugin, unsupported-server

**Comment by successed** [comment] 2019-05-29 03:34
> v2.7.0 has been released which provides support for Spigot 1.14.2.
> 
> If you run into any issues, or issues mentioned here are not resolved by that version yet, then please create new tickets for these issues and provide detailed information on how to reproduce them. Also make sure that you reproduce them on a fresh and up-to-date Spigot server, in order to ensure that those issues are not related to running an incompatible or snapshot build previously.

Can you give me link ?

**Comment by blablubbabc** [comment] 2019-05-29 08:19
> Can you give me link ?

https://dev.bukkit.org/projects/shopkeepers/files

It took a few hours for curse staff to review the upload.
