### ISSUE TITLE
Shopkeeper admin gui bug

### ISSUE THREAD

**Issue by KodxQ8** [Shopkeepers/Shopkeepers#586] opened 2019-07-09 20:53 UTC
## Preliminaries:

* **Shopkeepers version:** `Latest`
* **Spigot version:** `PAPER-107 1.14.2`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`<able / not able>`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`<Insert output of /version command on up-to-date Spigot server>`**) with the latest version of Shopkeepers (currently **`<Insert latest tested Shopkeepers version>`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

When i open the shopkeeper and try to press anything .. it just goes to my hand- cant delete or do anything to the shopkeeper

Include:
* Description of the issue.
* Step-by-step instructions on how to reproduce the issue.
* Observed behavior.
* Expected behavior.
* If items with special attributes are involved: Include instructions on how to create those items.
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
* If modified from default: Plugin configurations.
* .. Anything else that might be useful to reproduce and identify the issue.

**Comment by blablubbabc** [comment] 2019-07-09 21:06
* Can you try to reproduce this on an up-to-date Spigot server? Paper has some internal differences which makes it harder for me to figure out whether this is a Paper, Spigot, or plugin issue.
* Shopkeepers v2.7.2 only supports MC 1.14.**3**. There are some situations in which the combination of v2.7.2 and MC 1.14.2 will break,

> When i open the shopkeeper and try to press anything .. it just goes to my hand- cant delete or do anything to the shopkeeper

I cannot reproduce this behavior on an fresh Spigot server wihtout other plugins. So the issue has to be caused by something specific to your setup.
* Try to reproduce this without other plugins. If the issue disappears, try to pin down the conflicting plugin.
* Make sure that you are not using any client mods.
* Check your server log for errors.

**Comment by AidanWright** [comment] 2019-07-10 03:31
I was able to reproduce on `git-Spigot-d05d3c1-7ad3a1f` and `git-Spigot-6e94473-7ad3a1f` with a bungee backend

server plugins:
- BungeeTabListPlus
- PermissionsEx
- Plugman
- mcMMO
- MaSuiteCore
- MaSuiteChat
- MaSuitePortals
- Vault
- WorldEdit
and of course Shopkeepers

bungee plugins:
- BungeePexBridge
- BungeeTabListPlus
- HubConnector
- MaSuiteCore
- MaSuiteChat
- MaSuitePortals
- FakeProtocol
- StaffChat

I have no client mods and I am running the default minecraft launcher

When trying to click on any of the items in the chest I get the following error in console
```[Server thread/ERROR]: Could not pass event InventoryClickEvent to Shopkeepers v2.6.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2162) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[spigot.jar:git-Spigot-d05d3c1-7ad$
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:898) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:891) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:875) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:808) [spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getTitle()Ljava/lang/String;
        at com.nisovin.shopkeepers.ui.defaults.EditorHandler.isWindow(EditorHandler.java:667) ~[?:?]
        at com.nisovin.shopkeepers.ui.UIListener.validateSession(UIListener.java:40) ~[?:?]
        at com.nisovin.shopkeepers.ui.UIListener.onInventoryClick(UIListener.java:82) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot.jar:git-Spigot-d05d3c1-7ad3a1f]
        ... 17 more```

**Comment by AidanWright** [comment] 2019-07-10 03:59
also tried with no plugins and same error

**Comment by blablubbabc** [comment] 2019-07-10 12:57
@AidanWright Your error indicates that you are using an older version of Shopkeepers, which does not support newer versions of Spigot. Updating Shopkeepers should resolve your issue.

@KodxQ8 Do you get the same error? Which exact version of Shopkeepers are you using?

**Comment by andrius-t** [comment] 2019-07-10 13:33
I Have same problem I'm using 2.6.0 and 1.4.3 Paper

**Comment by andrius-t** [comment] 2019-07-10 13:38
Nvm I found newer version 2.7.2 in builds. I used the one from bukkit plugins link, which gives you 2.6.0 maybe the link needs to be updated

**Comment by blablubbabc** [comment] 2019-07-10 13:44
> I used the one from bukkit plugins link, which gives you 2.6.0 maybe the link needs to be updated

The link points to the latest 'release' version. However, since Spigot 1.14.x is itself still in development phase and not considered stable (updates are being made daily), corresponding Shopkeepers versions are marked as 'beta' as well.

**Comment by blablubbabc** [comment] 2019-07-22 00:15
Since no further information was provided by the topic creator, I assume the discussed issue matches this ticket and therefore close this as resolved.

**Closed by blablubbabc** 2019-07-22 00:15 UTC
Labels: cannot-reproduce, outdated-plugin
