### ISSUE TITLE
Suggestion: Multiple people for 1 shopkeeper

### ISSUE THREAD

**Issue by KironDevCoder** [Shopkeepers/Shopkeepers#616] opened 2019-09-20 18:36 UTC
## Preliminaries:

* **Shopkeepers version:** `idk, I don't own the server, I'm just doing an suggestion`
* **Spigot version:** `again, I don't own the server, so I can't do /version`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **`not able`** to reproduce my issue on a freshly setup and up-to-date Spigot server (currently **`idk what Spigot version`**) with Shopkeepers (currently **`again idk`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of your problem and add as much information as possible which could help reproducing the issue.

Include:
* Description of the issue.
I am making a shop with a friend but I can't open my friend's shopkeeper's chest (neither can he open mine)
* Step-by-step instructions on how to reproduce the issue.
just.... using it.... and making a shop with a friend
* Observed behavior.
I can't open his shopkeeper's chest
* Expected behavior.
Actually expect the same as observed
* If items with special attributes are involved: Include instructions on how to create those items.
none
* Server logs (from server startup until issue). Consider enabling debug mode in the config for additional console output.
idk I don't have access to that
* If modified from default: Plugin configurations.
probably not?
* .. Anything else that might be useful to reproduce and identify the issue.
it's just a suggestion for a command to add other people to a shopkeeper

**Comment by blablubbabc** [comment] 2019-09-21 00:59
Duplicate of: https://github.com/Shopkeepers/Shopkeepers/issues/342
There are still some open questions regarding this feature in the linked ticket. Maybe consider posting your ideas on those there. Especially: Does your friend need to be able to edit the shop (trades, mob attributes, shop name, removal permission), or would chest access be sufficient for your usecase?

**Closed by blablubbabc** 2019-09-21 00:59 UTC
Labels: duplicate
