### ISSUE TITLE
(Feature Request) ExecutableItems support

### ISSUE THREAD

**Issue by Reddishye** [Shopkeepers/Shopkeepers#896] opened 2024-07-08 19:29 UTC
## Preliminaries:

* **Shopkeepers version:** `2.22.1`
* **Spigot version:** `1.21`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

---

I was wondering if it would be able to add EI and maybe EB support. The way to do this is by making it just check the EI id.

![image](https://github.com/Shopkeepers/Shopkeepers/assets/46359630/ab4f8f2f-260f-40cd-be1b-fd4f7ce71a7c)

I know this might require modify vanilla behaviors, and that might be something too hard to implement/impossible to implement.

**Comment by blablubbabc** [comment] 2024-07-08 22:02
Duplicate of: https://github.com/Shopkeepers/Shopkeepers/issues/852

However, also not a high priority for me currently. Ideally, I would want any item plugin compatibility features implemented as separate addon-plugins, maybe even maintained by someone who uses the plugin in question.

**Closed by blablubbabc** 2024-07-08 22:02 UTC

**Comment by Reddishye** [comment] 2024-07-08 22:13
> Duplicate of: #852
> 
> However, also not a high priority for me currently. Ideally, I would want any item plugin compatibility features implemented as separate addon-plugins, maybe even maintained by someone who uses the plugin in question.

Is it possible to do it by using only the API, because if it is, i'll code it

**Comment by blablubbabc** [comment] 2024-07-08 22:38
> > Duplicate of: #852
> > However, also not a high priority for me currently. Ideally, I would want any item plugin compatibility features implemented as separate addon-plugins, maybe even maintained by someone who uses the plugin in question.
> 
> Is it possible to do it by using only the API? Because if it is, i'll code it

> The way to do this is by making it just check the EI id.
It is not possible to change the item comparison logic (results in client-side glitches if the server and MC client use different logic to decide whether a trade can be used or not).

However, my guess is that you would only need some way to update the shopkeeper trade items to match the latest revision defined by the ExecutableItems plugin whenever the ExecutableItems plugin, the Shopkeepers plugin, or your addon plugin are reloaded.

I.e. maybe some `Shopkeeper#updateItems()` method that can be invoked on individual shopkeepers, which calls a new `ShopkeeperUpdateItemEvent` for each trade item, as well as for any other stored item (e.g. the hire cost item of player shops, or equipment items stored by mobs (upcoming feature)). And there could be some top-level `ShopkeepersAPI#updateItems()` to invoke this for all shopkeepers, as well as for any other items stored by the plugin (e.g. currency items inside the config, etc.).
And your and other add-on plugins could then hook into the event, check if the item matches the item-plugin your addon is dealing with, and then replace the item with an updated version.
And the plugin would detect these changes, update the internal items / trades, and trigger a save of all changed data.

The same probably applies for these integrations as well:
* https://github.com/Shopkeepers/Shopkeepers/issues/773
* https://github.com/Shopkeepers/Shopkeepers/issues/789

I would be willing to add such an API to the plugin if you are willing to implement, make available, and maintain an open source add-on plugin available for Spigot that makes use of.

**Comment by Reddishye** [comment] 2024-07-09 12:43
> > > Duplicate of: #852
> > > However, also not a high priority for me currently. Ideally, I would want any item plugin compatibility features implemented as separate addon-plugins, maybe even maintained by someone who uses the plugin in question.
> > 
> > 
> > Is it possible to do it by using only the API? Because if it is, i'll code it
> 
> > The way to do this is by making it just check the EI id.
> 
> It is not possible to change the item comparison logic (results in client-side glitches if the server and MC client use different logic to decide whether a trade can be used or not).
> 
> However, my guess is that you would only need some way to update the shopkeeper trade items to match the latest revision defined by the ExecutableItems plugin whenever the ExecutableItems plugin, the Shopkeepers plugin, or your addon plugin are reloaded.
> 
> I.e. maybe some `Shopkeeper#updateItems()` method that can be invoked on individual shopkeepers, which calls a new `ShopkeeperUpdateItemEvent` for each trade item, as well as for any other stored item (e.g. the hire cost item of player shops, or equipment items stored by mobs (upcoming feature)). And there could be some top-level `ShopkeepersAPI#updateItems()` to invoke this for all shopkeepers, as well as for any other items stored by the plugin (e.g. currency items inside the config, etc.). And your and other add-on plugins could then hook into the event, check if the item matches the item-plugin your addon is dealing with, and then replace the item with an updated version. And the plugin would detect these changes, update the internal items / trades, and trigger a save of all changed data.
> 
> The same probably applies for these integrations as well:
> 
> * [[Feature Request] Add Oraxen support #773](https://github.com/Shopkeepers/Shopkeepers/issues/773)
> * [(Feature Request) MMOItems support. #789](https://github.com/Shopkeepers/Shopkeepers/issues/789)
> 
> I would be willing to add such an API to the plugin (no ETA) if you are willing to implement, make available, and maintain an open source add-on plugin available for Spigot that makes use of.

Yeah, I would maintain it

**Comment by Reddishye** [comment] 2024-07-09 13:35
In fact it would be only using the getExecutableItem method and then using the method you said

**Comment by blablubbabc** [comment] 2024-10-02 23:50
@Reddishye The discussed feature has been added in the latest snapshot version of the plugin: https://github.com/Shopkeepers/Shopkeepers/commit/20f67c999d3e06598cbb9df02beb0389ab171525

An example of how to use it can be found here: https://github.com/Shopkeepers/Shopkeepers-APISamples/tree/master/src/main/java/de/blablubbabc/shopkeepersAPISamples/itemUpdates

Let me know once you have an integration for ExecutableItems available on Spigot and Github. I will then link to it from the plugin page. If you have any questions let me know.

**Comment by Reddishye** [comment] 2024-10-17 19:42
Working on the integration, thanks for doing it <3
