### ISSUE TITLE
Shopkeeper BURNING ?! 

### ISSUE THREAD

**Issue by Denis4o26** [Shopkeepers/Shopkeepers#881] opened 2024-05-13 15:12 UTC
Hello ! I just started making a Minecraft server with aternos ! I downloaded the plugin ! And it works but when i set a shopkeeper he is just burning ?! Why is this happening !? 

![2024-05-13_18 09 49](https://github.com/Shopkeepers/Shopkeepers/assets/169686817/d891adc5-ccf3-411e-b04f-72524e3590db)

**Comment by Utlamo** [comment] 2024-05-21 17:55
In normal server burning too

**Comment by blablubbabc** [comment] 2024-05-26 10:18
Please provide additional information on how to reproduce this issue: Exact server version, plugin version, relevant configuration if any, server log if there are any warnings or errors. Try to reproduce the issue locally on an up-to-date Spigot server and without any other plugins.

**Comment by Utlamo** [comment] 2024-05-27 10:04
Hello 👋 So
Server:
This server is running Paper version git-Paper-78 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 3fc9358)
You are 34 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Purpur-2207 (MC: 1.20.6)
(killing all entity and setup after load new server engine dont work)

shopkeepers plugin:
2.19.1-SNAPSHOT+03d59d7f but latest release have same error so this is version build from github resource

So all plugins in screenshot:
![image](https://github.com/Shopkeepers/Shopkeepers/assets/47920580/a0dcbc54-069d-4d91-95f9-d0df7a4df1d7)

How to reproduce:
Setup any entity using shopkeeper plugin

 Logs:
[latest.log](https://github.com/Shopkeepers/Shopkeepers/files/15454300/latest.log)

If you need anything more let me know here

**Comment by blablubbabc** [comment] 2024-05-27 10:34
> Hello 👋 So Server: This server is running Paper version git-Paper-78 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: 3fc9358) You are 34 version(s) behind Download the new version at: https://papermc.io/downloads/paper Previous version: git-Purpur-2207 (MC: 1.20.6) (killing all entity and setup after load new server engine dont work)
> 
> shopkeepers plugin: 2.19.1-SNAPSHOT+03d59d7f but latest release have same error so this is version build from github resource
> 
> So all plugins in screenshot: ![image](https://private-user-images.githubusercontent.com/47920580/334057755-a0dcbc54-069d-4d91-95f9-d0df7a4df1d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDUxOTMsIm5iZiI6MTcxNjgwNDg5MywicGF0aCI6Ii80NzkyMDU4MC8zMzQwNTc3NTUtYTBkY2JjNTQtMDY5ZC00ZDkxLTk1ZjktZDBkZjdhNGRmMWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEwMTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODkzNWEyODljMGU5MmMyZDgwMmQ0OTFlZjEyODYxMDRkNWZmZmJhYmI3NjYzMGI2ZjE1OTJjN2EyODRlZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lCzJkLjCDQgLIXlgzsTMF4nOQQDTh4OFy9yiXO6L97Q)
> 
> How to reproduce: Setup any entity using shopkeeper plugin
> 
> Logs: [latest.log](https://github.com/Shopkeepers/Shopkeepers/files/15454300/latest.log)
> 
> If you need anything more let me know here

Version 2.19.1-SNAPSHOT+03d59d7f is known to not support MC 1.20.6 yet.
This ticket is therefore a duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/880 (this was not clear in the original issue description due to no mention of the server version).

Regarding the recently released 2.20.0 version of Shopkeepers not working on Paper servers: There is currently a fix pending to be released (v2.20.1). In my testing, this update should resolve the issue on Paper (I tested on build 107). If you want to, try this build and let me know if you can confirm that this version resolves these issues: https://github.com/Shopkeepers/Shopkeepers/actions/runs/9253326699

**Closed by blablubbabc** 2024-05-27 10:33 UTC
Labels: waiting
