### ISSUE TITLE
taking items from the editor.

### ISSUE THREAD

**Issue by skuras** [Shopkeepers/Shopkeepers#716] opened 2021-01-08 00:27 UTC
## Preliminaries:

* **Shopkeepers version:** `<Newest!>`
* **Spigot version:** `<Newest! 1.16.4>`
---

the only problem i have is that when im in the editor if i example click on change to or delete the shop ill take the item like ''delete the shop'' you have to click on the bone but when i do the shop is deleted BUT! the bone will be dropped same as any other thing in the editor. once' you click on change or any item in the editor you can take it. 

how to fix pls 
p.s im a really big fan of this plugin using it already for 2 years.
and for 4 servers.

**Comment by blablubbabc** [comment] 2021-01-08 02:23
I cannot reproduce this issue.

The plugin is cancelling any interaction with the inventory slot, so either some other plugin is interfering, the server has a bug (if you are not using Spigot), or this is a client side glitch (either caused by a client side mod, a plugin like ViaVersion or similar, or a server bug)

Try to reprodue this:
* On the latest version of Spigot (not some other type of server).
* Without client mods.
* Without other plugins.

**Comment by skuras** [comment] 2021-01-08 12:01
this is all the plugins im using atm 
![Screenshot (20210108-130023)](https://user-images.githubusercontent.com/77131126/104013388-a8eb8280-51b1-11eb-9de5-9400074fad70.jpg)

**Comment by blablubbabc** [comment] 2021-01-08 14:12
I don't know all of these plugins, so I can't tell if there is an incompatibility with one of them. Certainly try without the item related plugins to see if that resolves the issue. If not, test the setup I described above, and then make changes to that (changing server type/version, adding plugins, ..) until it breaks.

**Comment by luckofthelefty** [comment] 2021-01-15 00:32
I am having the same experiences as here. When I sneak to open the editor, the items act as items and not buttons. The only plugins I have in common with OP is LuckPerms, WorldEdit, and WorldGuard.

**Comment by blablubbabc** [comment] 2021-01-15 00:41
I am not aware of any issues with these plugin, so it is probably something different that is specific to your setup. Consider my other notes above. If this is not the case already, make sure that you are using the latest version of Spigot (and not some other type of server) and try to reproduce your issue there.

**Comment by luckofthelefty** [comment] 2021-01-15 02:01
I'll disable the plugins and restart. But yea its most recent versions of everything. Just set the server up yesterday.

**Comment by luckofthelefty** [comment] 2021-01-16 01:16
Just an update as I'm currently troubleshooting it, But I've been adding in plugins one by one and restarting the server. So far I've added in the ones I had in common with the OP and no issues. I thought it might've been a permissions thing with LuckPerms but its working as well. My next post I'll let you know which one is the culprit.

**Comment by blablubbabc** [comment] 2021-01-16 01:58
> Just an update as I'm currently troubleshooting it, But I've been adding in plugins one by one and restarting the server. So far I've added in the ones I had in common with the OP and no issues.

So, to clarify: The server is not the issue, the plugins you had in common are not the issue, and shopkeepers itself is not the issue? So it has to be a plugin compatibility issue then, with one (or more) of the remaining plugins (or a config difference).

**Comment by luckofthelefty** [comment] 2021-01-16 04:28
> > Just an update as I'm currently troubleshooting it, But I've been adding in plugins one by one and restarting the server. So far I've added in the ones I had in common with the OP and no issues.
> 
> So, to clarify: The server is not the issue, the plugins you had in common are not the issue, and shopkeepers itself is not the issue? That's already good to know since it cuts down the possible causes quite a lot. So it has to be a plugin compatibility issue then, with one (or more) of the remaining plugins (or a config difference).

Correct. I had to step away from troubleshooting because its tedious adding one restarting, checking lol. I'll get back to it after I get my kids to bed

**Comment by blablubbabc** [comment] 2021-01-16 13:21
> Correct. I had to step away from troubleshooting because its tedious adding one restarting, checking lol. I'll get back to it after I get my kids to bed

You can also add half of your plugins, and then either remove half of those again if the issue occurs, or continue adding half of the remaining plugins if it does not. That's a lot faster (max 7 steps for 100 pugins) ;)

**Comment by blablubbabc** [comment] 2021-02-01 06:30
Any news on this? Any progress with figuring out the conflicting plugin(s)?

**Comment by blablubbabc** [comment] 2021-02-18 13:12
Closing this since there has been no further information on how to reproduce this. My guess is still that this was likely caused by plugin incompatibilities. If anyone figures out the plugin(s) that are in conflict here, let me know so that I can either look into these incompatibilities or add a notice to the [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues) in the wiki.

**Closed by blablubbabc** 2021-02-18 13:12 UTC
Labels: cannot-reproduce

**Comment by blablubbabc** [comment] 2021-02-22 14:25
I believe the conflicting item in OP's case was InvSee. I reported the issue to the author of that plugin (https://www.spigotmc.org/threads/invsee-plugin-with-config-1-8-x-1-16-5.412888/#post-4093874) and added a note to the Known Issues inside the wiki.
