### ISSUE TITLE
Error when trying to load trades with custom spawn eggs with modified entity type

### ISSUE THREAD

**Issue by Hyronymos1337** [Shopkeepers/Shopkeepers#784] opened 2022-03-05 17:58 UTC
## Preliminaries:

* **Shopkeepers version:** `latest`
* **Spigot version:** `1.18.2`
---

## The issue: Offers of a Villiager are getting cleared, after Server restart

The Shopkeepers are made with Citizens (/trait shopkeeper)

Shopkeepers saves.yml: https://pastebin.com/XJT6VyN9

Error: https://pastebin.com/j1ti3h89

Server-Log: https://pastebin.com/pVnUkbMh

Plugin-List: ![image](https://user-images.githubusercontent.com/44213484/156894996-9dc46015-420a-496f-836d-3503585f6aff.png)

**Comment by blablubbabc** [comment] 2022-03-05 18:07
Can you attach your Shopkeepers save.yml file, ideally once from a backup from before the upgrade, and once after the failed upgrade attempt?

> Shopkeepers saves.yml: https://pastebin.com/XJT6VyN9
This file does not look like a valid Shopkeepers save.yml file. Instead this might be the save file of one of your other plugins.

**Comment by Hyronymos1337** [comment] 2022-03-05 18:10
> This file does not look like a valid Shopkeepers save.yml file. Instead this might be the save file of one of your other plugins.

we already re-created saves.yml, i will recreate it once again without the shopkeeper that makes problems

**Comment by Hyronymos1337** [comment] 2022-03-05 18:23
saves after restart (shopkeeper doesnt have items anymore): https://pastebin.com/sFf5zMF9

saves before restart (shopkeeper works like usal): https://pastebin.com/EUFJfNaH

**Comment by Hyronymos1337** [comment] 2022-03-05 18:25
Looks like the issue is the poal bear egg.

![image](https://user-images.githubusercontent.com/44213484/156895648-56cf7e71-50b0-47b3-a3b1-3fb5e124858c.png)

**Comment by blablubbabc** [comment] 2022-03-05 19:22
I haven't tested and compared the save files yet, but regarding the custom spawn egg item that is supposed to spawn a different kind of mob: This is not supported by Spigot currently. Relevant tickets:
* https://github.com/Shopkeepers/Shopkeepers/issues/718
* https://hub.spigotmc.org/jira/browse/SPIGOT-5485
Spigot consider spawn egg items with an entity tag as 'legacy' and attempts to automatically 'migrate' them. Since there is no spawn egg item for iron golems, this migration yields an empty item stack, which would then explain why the loading of the shopkeeper trade fails (all trades require a non-empty result item).

**Comment by blablubbabc** [comment] 2022-03-31 16:56
I am closing this since the cause of this issue is already tracked by the other mentioned ticket.

**Closed by blablubbabc** 2022-03-31 16:56 UTC
Labels: duplicate, bug
