### ISSUE TITLE
Shop Keepers jumping

### ISSUE THREAD

**Issue by lukeeexd** [Shopkeepers/Shopkeepers#523] opened 2018-09-04 13:02 UTC
Paper version git-Paper-213 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
Shopkeepers-2.4.0.jar

https://streamable.com/5hlk9 Why do shopkeepers jump?

**Comment by blablubbabc** [comment] 2018-09-10 18:03
All shopkeeper entities get teleported back to their original spawn location every 10 seconds, if they for some reason move further than ~0.5 blocks. 
When placing a shopkeeper, it spawns it in the middle of the block **above** the block you are targeting (if you are targeting the top face of a block). So if you target some non-solid (passable) block (like grass, flowers, ..) or a non-1x1x1-block (like snow, flower pots, plates, .. or like in your case: carpets) then the actual spawn location will currently be 1 block above that. The spawned shopkeeper will then however fall 'into' the block below it (due to gravity), resulting in the periodic back-teleportation every ~10 seconds (the 'jumping' you observe).

I am aware of this 'inconvenience', but haven't come around yet to fix it (though I did some preparation with the latest updates by refactoring the shopkeeper creation and by having to check block bounding boxes for the custom gravity behavior already).
This would probably be easier to fix if Bukkit had some sort of API for checking if a block is passable or, more general, for getting the exact bounding box of a block. (I haven't come around yet to provide Spigot with a corresponding addition PR for this, but you can consider upvoting this corresponding spigot ticket: https://hub.spigotmc.org/jira/browse/SPIGOT-2151, so maybe someone else picks it up)

**Comment by AncientTom** [comment] 2018-09-11 15:07
Not a bug, It's a feature, of Minecraft that is. It's nice to know this. All I have to do is remove my red carpet and replace the block below it with red wool. Easy, Peasy! I wouldn't try to fix this since this is the natural order of Minecraft. The best thing you could do is to update all documentation to inform users that this is the case when placing a Shopkeeper.

**Comment by blablubbabc** [comment] 2018-09-11 15:17
You can also remove the carpet, then place the shopkeeper there, then re-add the carpet. That should work as well.

**Comment by blablubbabc** [comment] 2018-10-27 14:17
This will be fixed / improved with the next update: Shopkeepers will then spawn exactly where they are meant to be within a range of 1 block below their spawn block, and only back-teleport ('jump') if their current location is further away then that.

**Comment by blablubbabc** [comment] 2019-02-16 12:01
Fixed in v2.5.0

**Closed by blablubbabc** 2019-02-16 12:01 UTC
Labels: accepted, enhancement
