### ISSUE TITLE
shopkeeper disappeared when i change it name to (-)

### ISSUE THREAD

**Issue by filiperose** [Shopkeepers/Shopkeepers#499] opened 2018-04-07 06:18 UTC
my shopkeeper disappeared when i change it name to - (dash)

**Comment by blablubbabc** [comment] 2018-04-07 13:29
I assume you used the Shop-Renaming-Option in the editor and then types dash in the chat? I cannot reproduce this issue. For me it clears the shop's name as it should.

Which plugin version and which spigot version are you using? Also, could you try to reproduce this on a server without any other plugins?

**Comment by filiperose** [comment] 2018-04-08 03:31
i use 1.12 spigot server and latest shopkeeper.

**Comment by blablubbabc** [comment] 2018-04-08 11:46
I cannot reproduce this with the latest spigot server and latest shopkeeper version. So this issue has to be caused by something else specific to your setup, most likely a conflicting plugin.

Try to reproduce this without other plugins, and then try to figure out which of your other plugins might be interferring by adding them one by one until this issue occurs.

**Comment by blablubbabc** [comment] 2018-05-17 22:50
Closing this as no further information was provided that could help reproducing this issue.

**Closed by blablubbabc** 2018-05-17 22:50 UTC
Labels: cannot-reproduce, waiting
