### ISSUE TITLE
Shopkeeper trading issue

### ISSUE THREAD

**Issue by TDSkitz** [Shopkeepers/Shopkeepers#496] opened 2018-03-17 18:14 UTC
I setup a shopkeeper with pickaxes, they have Custom names, are unbreakable, and can only destoy specific blocks.  My issue it, whenever the villager refreshes itself, if you have one of the picks from before it refreshed you cant use that pick in the trade anymore.  I tested it in a fresh server and had the same issue.  I tried research online but I coudlnt find anything so I came here for help.

**Comment by blablubbabc** [comment] 2018-03-17 18:23
Could you give me (minimal) setup instructions on how I can create those pickaxes on a fresh spigot server and which other plugins need to be present in order to reproduce this?
Also, make sure you that you have tested this issue with spigot and not some other server version (paper, ..).

**Comment by TDSkitz** [comment] 2018-03-17 18:27
I use /give @p minecraft:wooden_pickaxe 1 0 {Unbreakable:1,CanDestroy:["minecraft:stone","minecraft:coal_ore"]} to gie me the pick axes, then I use the plugin ItemEdit to rename them /itemedit rename &6&lWooden Pick &7&lTier 1

**Comment by TDSkitz** [comment] 2018-03-17 18:44
I removed the names from the picks and now they work fine, but Im confused as I have another villager working fine wiht custom names on blocks.

**Comment by blablubbabc** [comment] 2018-03-17 21:28
I have tested this on a spigot 1.12.2 server and was not able to reproduce this issue, even with the item renamed with ItemEdit and several shopkeeper reloads/refreshes in between.
I also looked into ItemEdit and didn't see any issue with how it is renaming items.

Maybe you could try again and let me know what exactly you are doing differently.

**Comment by blablubbabc** [comment] 2018-05-17 22:48
Closing this as no further information was provided that could help reproducing the issue.

**Closed by blablubbabc** 2018-05-17 22:48 UTC
Labels: cannot-reproduce, waiting
