### ISSUE TITLE
Support for custom heads

### ISSUE THREAD

**Issue by Tobiczek** [Shopkeepers/Shopkeepers#838] opened 2023-08-19 08:49 UTC
Hey, recently I've been trying to analyze what exactly bugs my shoppkers, I encountered a problem when working with heads
![image](https://github.com/Shopkeepers/Shopkeepers/assets/114435370/837a3ffe-63a9-421e-85fe-dee01502d3f8)

**Comment by Tobiczek** [comment] 2023-08-19 08:50
I have "eco" plugins, I once reported a problem, but in the end it turned out that it is not incompatible with Eco plugins, but it's about the heads

**Comment by blablubbabc** [comment] 2023-08-19 11:17
> I have "eco" plugins, I once reported a problem, but in the end it turned out that it is not incompatible with Eco plugins, but it's about the heads

Please try to reproduce any issues on an an empty and up-to-date Spigot server without any other plugins. I don't have the time to investigate the internals of other plugins or custom server implementations to figure out how they might possibly interfere with the Shopkeepers plugin.

You can also try to turn on the `/shopkeeper debug` mode, then reattempt the trade, and check the server log for additional information. Maybe this yields some additional useful information that might help identify the problem.

Regarding head items: There is some information on potential issues with them inside the wiki: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues

If you can reproduce the issue on an empty server without other plugins, the issue might be dependent on how you create the player head item in the first place. If you have some vanilla Minecraft give command to create a player head item, I can try to reproduce it.

Unless I have a way to reproduce the issue on an empty Spigot server, I will not be looking into this issue.

**Comment by blablubbabc** [comment] 2023-09-30 09:45
Closing this since no further information was provided regarding the exact items involved and how to reproduce the issue on an other wise empty Spigot server.

**Closed by blablubbabc** 2023-09-30 09:45 UTC
Labels: waiting
