### ISSUE TITLE
Compatibility issue with Eco items items

### ISSUE THREAD

**Issue by pjindras** [Shopkeepers/Shopkeepers#925] opened 2024-10-22 09:03 UTC
## Preliminaries:

* **Shopkeepers version:** `2.23.0`
* **Spigot version:** `Always latest Paper version for 1.21.1`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## The issue:

Provide a detailed description of the issue and information on how to reproduce it.

There is an issue with Eco items plugin and its items, because when I use eco items item in shopkeepers, the trade often doesnt work, the tags and all the item components are exactly the same.

Could you please help? I am sure, that there must be some compatibility issue, because if I use other item than ecoitems item, it works fine.

I contacted both sides (eco and you).

**Comment by pjindras** [comment] 2024-10-22 11:09
and I often see this error: https://mclo.gs/2wrkvL7

**Comment by blablubbabc** [comment] 2024-11-02 13:29
> and I often see this error: https://mclo.gs/2wrkvL7

This error should be unrelated to Eco and will be fixed with the next plugin update. It is caused by some internal change in Spigot, for which the plugin needs to be recompiled against the latest Spigot version.

**Comment by blablubbabc** [comment] 2024-11-02 13:33
Shopkeepers and the Eco plugins have a long history of not eing compatible. See the https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues page insied the wiki.

The last time I checked (a few years ago), the Eco plugin would try to dynamically update the item data in the packets sent by the server to clients in order to hide or add certain item information (for visual purposes). And in doing that it would (not sure if accidentally or intentionally) also modify the actual item data on the server (i.e. the data of the items used inside the Shopkeeper trades). In order to avoid unexpected issues, the Shopkeepers plugin does not support these unexpeted modifications to the item data and decides to cancel any trade attempts if it detects changes to the items involved.

But this is based on analysis from years ago. I do not know if something has changed in Eco since then, nor do I intend ti invest any more time into investigating this incompatibility.

**Closed by blablubbabc** 2024-11-02 13:33 UTC
Labels: declined, incompatibility
