### ISSUE TITLE
No trade with a shopkeeper

### ISSUE THREAD

**Issue by Gartentrulla** [Shopkeepers/Shopkeepers#609] opened 2019-08-18 17:24 UTC
## Preliminaries:

* **Shopkeepers version:*2.7.2* `<Insert Shopkeepers version>`
* **Spigot version:*1.14.4* `<Insert output of /version command>`
---

Please can you update shopkeepers for the new spigot Version 1.14.4.
There are no errors, but it dosn't work. Not for user, owner and with op.
Thank you and sorry my english, I'm german

**Comment by blablubbabc** [comment] 2019-08-18 19:39
Can you clarify the issue you are having? What exactly "isn't working"? What are you trying to do, what steps are you performing, what do you expect to happen and what happens instead?
Also check your server's startup log to look for any errors.

I just tested Shopkeepers v2.7.2 on the very latest version of Spigot 1.14.4, and I am not encountering any issues.

**Comment by Gartentrulla** [comment] 2019-08-18 21:14
Hello blablubbabc,
thank you for your quick answer.
First I have no errors in my logs. Also not during the game. I use citizens2.0.25-b-1743 and both worked in the 1.14.3. Today I changed to 1.14.4 and I can’t take any Items from the shopkeeper. I put one in the field, but it is not possible to take the other one.

I tried a normal shopkeeper als a villager and it is the same. I can’t trade with them.

I generatet the config new, enbled citizens but nothing will work. I give you my config, maybe I interpreted something wrong. Just I testet on my local server but it is the same.

Thanks for your help.

Your Gartentrulla from Germany

**Comment by blablubbabc** [comment] 2019-08-18 21:34
So if the issue is with the trading: Can you enable the 'debug mode' in the config and then try the trade again? Maybe it prints something useful to the config.
Also try a trade with regular item (without any special item data).
If nothing helps, try without other plugins on the server. For example, setup a fresh local server for testing and only install shopkeepers.

My guess is that it's either something related to the item you are trying to trade, or some plugin compatibility issue.

**Comment by Gartentrulla** [comment] 2019-08-19 08:38
Good morning blablubbabc,
thanks again fr your answer.
Now I tried the debug mode and there I found, that all items which are enchanted don’t work. So I can’t tak an enchanted written book or an enchanted item which I generatet  or a playerhaed. Only the normal minecraft items works.

But how can I fix this? 

Here it is what the debug mode say:

Loading 1 shopkeepers in chunk karibikdreams,176,156
[10:13:48] [Server thread/INFO]: [Shopkeepers] Inventory click: player=Gartentrulla, view-type=MERCHANT, view-title=§2Votemarke, raw-slot-id=5, slot-id=11, slot-type=CONTAINER, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PICKUP_ALL
[10:13:49] [Server thread/INFO]: [Shopkeepers] Inventory click: player=Gartentrulla, view-type=MERCHANT, view-title=§2Votemarke, raw-slot-id=0, slot-id=0, slot-type=CRAFTING, shift=false, hotbar key=-1, left-or-right=right, click-type=RIGHT, action=PLACE_ONE
[10:13:50] [Server thread/INFO]: [Shopkeepers] Inventory click: player=Gartentrulla, view-type=MERCHANT, view-title=§2Votemarke, raw-slot-id=5, slot-id=11, slot-type=CONTAINER, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PLACE_ALL
[10:14:02] [Server thread/INFO]: [Shopkeepers] Inventory click: player=Gartentrulla, view-type=MERCHANT, view-title=§2Votemarke, raw-slot-id=2, slot-id=2, slot-type=RESULT, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PICKUP_ALL
[10:14:02] [Server thread/INFO]: [Shopkeepers] Not handling trade: The trade result item doesn't match the expected item of the used trading recipe!
[10:14:03] [Server thread/INFO]: [Shopkeepers] Inventory click: player=Gartentrulla, view-type=MERCHANT, view-title=§2Votemarke, raw-slot-id=2, slot-id=2, slot-type=RESULT, shift=false, hotbar key=-1, left-or-right=left, click-type=LEFT, action=PICKUP_ALL
[10:14:03] [Server thread/INFO]: [Shopkeepers] Not handling trade: The trade result item doesn't match the expected item of the used trading recipe!

I tried to change an ink sack to a Votemarke which is enchanted, and it dosn’t work. And I have enchanted keys from crazycrates, it is the same, I don’t get the Item.

Can you help?

Thanks a lot and best regards from Gartentrulla

**Comment by blablubbabc** [comment] 2019-08-19 09:15
The given log mentions that the items required by and passed to the trade are not matching.
Can you attach your config settings for those enchanted items? And also provide instructions how I can create those enchanted items you are passing to the trade?

**Comment by Gartentrulla** [comment] 2019-08-19 15:31
Hallo blablubbabc,
thanks a lot for your help. I could resolve the problem. It was a little bit difficulty. 

First I changed in the config  “use-strict-item-comparison: true” from false to true. Than I tried to reload the config, and test it, but it dosen’t work, so I startet the server new. After that I changed the enchanted item again to a normal item and it works. After that I put the enchanted item back and it works.

I only had to do it once, all the other works too. I did it with all the Shopkeepers which has enchanted items, and all Shopkeepers works after that.

Maybe someone has a nearly problem, than you can help directly.

So it is no issue, more a diffrent to the new version.

With best regards your Gartentrulla

**Comment by blablubbabc** [comment] 2019-08-19 18:10
Like I said, the issue is likely with those items you were using. If you were to post how you created those items / how I can create those items on my test server, I can see what is wrong with them. If you created those items with a plugin, it's likely an issue of that plugin. Otherwise it's either an issue with the command you used (if you created them via the minecraft command), or a Spigot issue (if the server doesn't persist the item's data throughout its interactions with the item).

Actions like interacting with the item, moving it around in the inventory, saving and loading it inside a shopkeeper can all modify the item if it is not in a 'normalized' form.

**Comment by Gartentrulla** [comment] 2019-08-20 14:44
Hallo blablubbabc,
it is a little bit diffiycult to explain it in english. But I will try and I hope you understand it.

In one shopkeeper I have a written book with own words. I signed it and put it into the shopkeeper. 

The second item is a light_blue_dye, which is renamend with the plugin lore to Textmarke and than enchanted with the minecraftbook protction1 in the amboss. That’s all.

From Minecraftversion 1.13 until 1.14.3 it works perfect, no problems. Only if I changed to 1.14.4 it doesn‘t work. I used no other plugin to create the items.

Now it works and if had nearly problems in the future I try first to remove the item and than put it back again.

With best regards your Gartentrulla

**Comment by blablubbabc** [comment] 2019-08-20 23:06
I just tried the following: Written some text into a book-and-quill book, signed it, renamed a blue dye to "Textmarke" in the anvil and enchanted it via the enchantment book from the creative menu with Protection IV. Then setup a trade: The signed book being sold for the custom blue dye. And that seems to work fine for me.

* Are you using some command or plugin to create that enchantment book for Protection I, or to enchant the item?
* Not exactly sure which plugin you used for the naming. This (quite outdated) one?: https://dev.bukkit.org/projects/lores  . If you rename the item in a regular anvil, does it work then?

Since it now works for you for some reason, it is probably no longer possible to reliable reproduce the issue and check if some of those actions make it work. So I will close this issue. If the issue occurs again, try to reproduce it with as few plugins involved to rule out those being the issue.

**Closed by blablubbabc** 2019-08-20 23:06 UTC
Labels: cannot-reproduce, waiting
