### ISSUE TITLE
Every time I want to place a shopkeeper a message is displayed

### ISSUE THREAD

**Issue by Smartiiii** [Shopkeepers/Shopkeepers#873] opened 2024-03-31 22:00 UTC
## Preliminaries:

* **Shopkeepers version:** `<2.15.1>`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Bukkit server:

I was able to reproduce my issue on a freshly set up and up-to-date Bukkit server with the 1.18.2 version of Shopkeepers, with no other plugins and with no kinds of other server or client mods.

## The issue:

Every time I want to place a shopkeeper a message is displayed: "You must specify a spawn location for this type of shop", i dont know what to do?

I want to place a shopkeeper i set up the egg and everything, but when I want to place i on the ground the message appers
I have the server in Bukkit and shopkeepers wont work (I have the Shopkeeper Bukkit 2.15.1)
it worked on aternos without a problem but on titanax it doesn't work

**Comment by blablubbabc** [comment] 2024-04-01 12:14
This message is rather unexpected to come up. There is an internal check to verify that a spawn location was specified and that the world of the spawn location is still loaded, for example if the shop is created by another plugin via the API. However, when creating the shop normally, those conditions are expected to always be fulfilled, since the spawn location is taken from the block you are interacting with, which naturally is expected to be "loaded" currently.

But maybe there is some kind of issue with this "is world loaded" check on your server. Can you check the following:
* Try Shopkeepers v2.19.0: This latest plugin version should be compatible with MC 1.18.2.
* Can you attach the exact server type and version here? I.e. the output of the `/version` command. If you are not using Spigot, or if you are not using Spigot version 3498 (the latest for MC 1.18.2), please try to reproduce the issue on a fresh Spigot 1.18.2-3498 server. The "is world loaded" check mentioned above is implemented by the server, so if there is an issue with that it could be caused by the server.
* Are you using any world management plugins? If yes, can you try to reproduce the issue without them, in the default world.
* Make sure that you don't have multiple worlds on disk with a similar name (e.g. `World` and `world`) or uid (uid.dat and level.dat files should be different for each world).

**Comment by blablubbabc** [comment] 2024-06-18 14:42
Closing this as no further information was provided on how to reproduce this issue.

**Closed by blablubbabc** 2024-06-18 14:42 UTC
Labels: waiting
