### ISSUE TITLE
Paper Server assumption test failed

### ISSUE THREAD

**Issue by DisguistingPublisher2814** [Shopkeepers/Shopkeepers#875] opened 2024-04-20 16:30 UTC
![image](https://github.com/Shopkeepers/Shopkeepers/assets/167637742/2ae72aac-a459-4d8e-888f-6cc3280d82d2)

`Starting org.bukkit.craftbukkit.Main
System Info: Java 22 (Java HotSpot(TM) 64-Bit Server VM 22+36-2370) Host: Windows 11 10.0 (amd64)
Loading libraries, please wait...
2024-04-20 19:14:43,789 ServerMain ERROR Rewrite contains an invalid element or attribute "ExtraClassInfoRewritePolicy"
[19:14:51 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[19:14:53 INFO]: Loaded 1174 recipes
[19:14:53 INFO]: Loaded 1271 advancements
[19:14:53 INFO]: Starting minecraft server version 1.20.4
[19:14:53 INFO]: Loading properties
[19:14:53 INFO]: This server is running Paper version git-Paper-489 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 3af1346)
[19:14:54 INFO]: Server Ping Player Sample Count: 12
[19:14:54 INFO]: Using 4 threads for Netty based IO
[19:14:54 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[19:14:54 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[19:14:55 INFO]: Default game type: SURVIVAL
[19:14:55 INFO]: Generating keypair
[19:14:55 INFO]: Starting Minecraft server on 192.168.1.37:25565
[19:14:55 INFO]: Using default channel type
[19:14:55 INFO]: Paper: Using Java compression from Velocity.
[19:14:55 INFO]: Paper: Using Java cipher from Velocity.
[19:14:56 WARN]: [org.bukkit.craftbukkit.v1_20_R3.legacy.CraftLegacy] Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[19:14:58 WARN]: Legacy plugin TreeCapitator v1.0 does not specify an api-version.
[19:14:59 WARN]: Legacy plugin ItemStacker v1.03 does not specify an api-version.
[19:14:59 INFO]: [Vault] Loading server plugin Vault v1.7.3-b131
[19:14:59 INFO]: [TabTPS] Loading server plugin TabTPS v1.3.22
[19:14:59 INFO]: [InvSee++] Loading server plugin InvSeePlusPlus v0.26.0
[19:14:59 INFO]: [Essentials] Loading server plugin Essentials v2.21.0-dev+78-c60ed56
[19:14:59 INFO]: [BeastLib] Loading server plugin BeastLib v1.4
[19:14:59 INFO]: [TreeCapitator] Loading server plugin TreeCapitator v1.0
[19:14:59 INFO]: [SkinsRestorer] Loading server plugin SkinsRestorer v15.0.10
[19:14:59 INFO]: [Shopkeepers] Loading server plugin Shopkeepers v2.19.0
[19:14:59 INFO]: [Shopkeepers] Loaded all plugin classes (507 ms).
[19:14:59 INFO]: [Shopkeepers] Loading config.
[19:15:00 INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[19:15:00 INFO]: [Shopkeepers] Registering defaults.
[19:15:00 INFO]: [ItemStacker] Loading server plugin ItemStacker v1.03
[19:15:00 INFO]: [InvSee++_Give] Loading server plugin InvSeePlusPlus_Give v0.26.0
[19:15:00 INFO]: [InvSee++_Clear] Loading server plugin InvSeePlusPlus_Clear v0.26.0
[19:15:00 INFO]: [GSit] Loading server plugin GSit v1.8.0
[19:15:00 INFO]: [EconomyShopGUI] Loading server plugin EconomyShopGUI v6.5.1
[19:15:00 INFO]: [Chunky] Loading server plugin Chunky v1.3.136
[19:15:00 INFO]: [BeastWithdraw] Loading server plugin BeastWithdraw v2.3.2
[19:15:00 INFO]: Server permissions file permissions.yml is empty, ignoring it
[19:15:00 INFO]: [Vault] Enabling Vault v1.7.3-b131
[19:15:00 INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[19:15:00 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[19:15:00 INFO]: [Vault] Enabled Version 1.7.3-b131
[19:15:00 INFO]: [SkinsRestorer] Enabling SkinsRestorer v15.0.10
[19:15:01 INFO]: [SkinsRestorer] Running on Minecraft 1.20.4.
[19:15:01 INFO]: [SkinsRestorer] Using paper join listener!
[19:15:01 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[19:15:01 WARN]: The server will make no attempt to authenticate usernames. Beware.
[19:15:01 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[19:15:01 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[19:15:01 INFO]: Preparing level "world"
[19:15:01 INFO]: [SkinsRestorer] ----------------------------------------------
[19:15:01 INFO]: [SkinsRestorer]     +==================+
[19:15:01 INFO]: [SkinsRestorer]     |   SkinsRestorer  |
[19:15:01 INFO]: [SkinsRestorer]     |------------------|
[19:15:01 INFO]: [SkinsRestorer]     |  Standalone Mode |
[19:15:01 INFO]: [SkinsRestorer]     +==================+
[19:15:01 INFO]: [SkinsRestorer] ----------------------------------------------
[19:15:01 INFO]: [SkinsRestorer]     Version: 15.0.10
[19:15:01 INFO]: [SkinsRestorer]     Commit: 91d1568
[19:15:01 INFO]: [SkinsRestorer]     This is the latest version!
[19:15:01 INFO]: [SkinsRestorer] ----------------------------------------------
[19:15:02 INFO]: Preparing start region for dimension minecraft:overworld
[19:15:02 INFO]: Time elapsed: 178 ms
[19:15:02 INFO]: Preparing start region for dimension minecraft:the_nether
[19:15:02 INFO]: Time elapsed: 30 ms
[19:15:02 INFO]: Preparing start region for dimension minecraft:the_end
[19:15:02 INFO]: Time elapsed: 30 ms
[19:15:02 INFO]: [TabTPS] Enabling TabTPS v1.3.22
[19:15:02 INFO]: [TabTPS] Successfully registered Mojang Brigadier support for commands.
[19:15:02 INFO]: [TabTPS] Successfully registered asynchronous command completion listener.
[19:15:03 INFO]: [InvSee++] Enabling InvSeePlusPlus v0.26.0
[19:15:03 INFO]: [Essentials] Enabling Essentials v2.21.0-dev+78-c60ed56
[19:15:03 INFO]: [Essentials] Attempting to convert old kits in config.yml to new kits.yml
[19:15:03 INFO]: [Essentials] No kits found to migrate.
[19:15:04 INFO]: [Essentials] Loaded 39095 items from items.json.
[19:15:04 INFO]: [Essentials] Using locale tr_TR
[19:15:04 INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[19:15:04 INFO]: [Essentials] Starting Metrics. Opt-out using the global bStats config.
[19:15:04 INFO]: [Vault] [Economy] Essentials Economy hooked.
[19:15:04 INFO]: [Essentials] Using superperms-based permissions.
[19:15:04 INFO]: [BeastLib] Enabling BeastLib v1.4
[19:15:04 INFO]: [BeastLib] Loading library triumph-gui
[19:15:04 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[19:15:04 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: Defaulting to no-operation (NOP) logger implementation
[19:15:04 ERROR]: [STDERR] [org.slf4j.helpers.Util] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[19:15:04 INFO]: [BeastLib] Loading library adventure-api
[19:15:04 INFO]: [BeastLib] Loading library adventure-key
[19:15:04 INFO]: [BeastLib] Loading library examination-api
[19:15:04 INFO]: [BeastLib] Loading library examination-string
[19:15:04 INFO]: [BeastLib] Loading library annotations
[19:15:04 INFO]: [BeastLib] Loading library adventure-text-serializer-legacy
[19:15:04 INFO]: [BeastLib] Loading library adventure-text-serializer-gson
[19:15:04 INFO]: [BeastLib] Loading library gson
[19:15:04 INFO]: [BeastLib] Loading library item-nbt-api
[19:15:04 INFO]: [BeastLib] Loading library mysql-connector-j
[19:15:04 INFO]: [BeastLib] Loading library HikariCP
[19:15:04 INFO]: [BeastLib] Loading library mongo-java-driver
[19:15:04 INFO]: [BeastLib] Loading library quartz
[19:15:04 INFO]: [TreeCapitator] Enabling TreeCapitator v1.0*
[19:15:04 INFO]: [Shopkeepers] Enabling Shopkeepers v2.19.0
[19:15:04 ERROR]: [Shopkeepers] Server assumption test failed: Bukkit ItemStack#isSimilar(Deserialized ItemStack)
[19:15:04 ERROR]: [Shopkeepers] Server incompatibility detected! Disabling the plugin!`

And if i use any commands 

`[19:29:46 INFO]: santakhan issued server command: /shopkeepers
[19:29:46 ERROR]: null
org.bukkit.command.CommandException: Cannot execute command 'shopkeepers' in plugin Shopkeepers v2.19.0 - plugin is disabled.
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:37) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:999) ~[paper-1.20.4.jar:git-Paper-489]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-489]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:31) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2230) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2190) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-489]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-489]
        at java.lang.Thread.run(Thread.java:1570) ~[?:?]`

how can i fix that itemstack issue please help

**Comment by blablubbabc** [comment] 2024-04-20 18:44
I am not able to reproduce the issue, using Shopkeepers v2.19.0 and Paper `git-Paper-491 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: c5f68ff)`.

On Discord, some user reported that they resolved the issue by using these java flags when starting the server `-Duser.language=en -Duser.region=EN -Dfile.encoding=UTF-8`. However, I am not sure how those flags would be related to the item serialization test that the plugin performs, not was I able to reproduce the issue with or without these flags on my machine.

**Comment by blablubbabc** [comment] 2024-06-08 10:19
My guess is that this issue is the same as this one: https://github.com/Shopkeepers/Shopkeepers/issues/886

There has been a fix for this in the upstream Spigot server. However, it won't be backported to 1.20.4. So the workaround on older server versions is to specify the startup parameters as mentioned by me above (language and region).

**Closed by blablubbabc** 2024-06-08 10:19 UTC
Labels: duplicate
