### ISSUE TITLE
1.13.1 shopkeepers

### ISSUE THREAD

**Issue by Ardno123** [Shopkeepers/Shopkeepers#556] opened 2019-03-23 18:12 UTC
when will minecraft plugin shopkeepers come out for 1.13.1?

(P.S. Sorry, I don't know, for 1.13.1)

**Comment by blablubbabc** [comment] 2019-03-24 16:05
Duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/555

Shopkeepers is already available for 1.13.1.

**Closed by blablubbabc** 2019-03-24 16:05 UTC
