### ISSUE TITLE
Updating the server removes the items of Shopkeepers.

### ISSUE THREAD

**Issue by eliyash31** [Shopkeepers/Shopkeepers#691] opened 2020-09-20 09:44 UTC
Hello just every time I update the server, the shopkeepers, remove the items or don't have the existing items they are selling anymore. I have to put back again the items that the shopkeeper is selling. 

I have tried it 2 times for now, the update really cause the items to be removed from the shopkeeper.

**Comment by blablubbabc** [comment] 2020-09-20 19:00
I cannot reproduce this without further information. Consider attaching your save data for the shopkeeper in question from before you update. Also, I assume you mean the update from 1.16.2 to 1.16.3? Otherwise you need to clarify. Also, I assume you are not updating shopkeepers but only the server.

Could be related to https://hub.spigotmc.org/jira/browse/SPIGOT-5964, but without further information I can't tell.

**Comment by blablubbabc** [comment] 2020-12-28 08:12
Closing this as no further information was provided. Feel free to come back to this with a save.yml file and information on how I can reproduce this issue.

**Closed by blablubbabc** 2020-12-28 08:12 UTC
Labels: cannot-reproduce, waiting
