### ISSUE TITLE
Instant heal

### ISSUE THREAD

**Issue by metal-overlord** [Shopkeepers/Shopkeepers#483] opened 2017-11-25 15:13 UTC
plz help me.
if i open villager menu i get forever instant heal.
how to turn it off?

**Comment by blablubbabc** [comment] 2017-11-25 16:07
I don't think this is related to this plugin. Try to reproduce your issue on a fresh spigot server with no other plugins running.

**Comment by blablubbabc** [comment] 2018-01-17 08:16
Closing this as no further information was provided and I cannot reproduce this.

**Closed by blablubbabc** 2018-01-17 08:16 UTC
Labels: cannot-reproduce
