### ISSUE TITLE
All Shopkeepers are admin

### ISSUE THREAD

**Issue by Jay33t** [Shopkeepers/Shopkeepers#636] opened 2020-03-04 19:35 UTC
I've removed all admin permissions from shopkeepers yet they still become admin shopkeepers.

**Comment by blablubbabc** [comment] 2020-03-04 19:48
Can you clarify what exactly you are doing, what the plugin is doing and what you expect it to be doing instead?

Maybe the issue is simply with how you attempt to create the player shops. In that case, see the wiki on that: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Creating-Shops#shop-creation

If the issue is related to regular players being able to create admin shops even though they should not be able to: In that case check your permissions setup. Some permissions are also given by default (eg. op players have the admin shop permission by default), so you will need to configure your permission plugin to explicitly remove that permission. Since every permissions plugin works differently I can't help you with that. You will need to figure this out according to your permission plugin's documentation. Check if your permissions plugin has a command for testing individual permissions, since that may be helpful for testing your permissions setup. Some plugins also cannot cope with server reloading, or require the player to rejoin in order to apply the updated permissions.

**Comment by Jay33t** [comment] 2020-03-04 19:58
> Can you clarify what exactly you are doing, what the plugin is doing and what you expect it to be doing instead?
> 
> Maybe the issue is simply with how you attempt to create the player shops. In that case, see the wiki on that: https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Creating-Shops#shop-creation
> 
> If the issue is related to regular players being able to create admin shops even though they should not be able to: In that case check your permissions setup. Some permissions are also given by default (eg. op players have the admin shop permission by default), so you will need to configure your permission plugin to explicitly remove that permission. Since every permissions plugin works differently I can't help you with that. You will need to figure this out according to your permission plugin's documentation. Check if your permissions plugin has a command for testing individual permissions, since that may be helpful for testing your permissions setup. Some plugins also cannot cope with server reloading, or require the player to rejoin in order to apply the updated permissions.

all i want is for people to make shopkeepers and be able to trade with them but im struggling to get it to work

**Comment by blablubbabc** [comment] 2020-03-04 20:00
It should work right our of the box. So what exactly are you doing and what isn't working?

**Comment by blablubbabc** [comment] 2020-05-08 09:42
Closing this are no further information has been provided.

**Closed by blablubbabc** 2020-05-08 09:42 UTC
Labels: invalid, plugin-help
