### ISSUE TITLE
Item rubber band

### ISSUE THREAD

**Issue by Marplee** [Shopkeepers/Shopkeepers#508] opened 2018-07-17 16:15 UTC
I am currently running a 1.12.2 server and running into a bit of an issues. I am able to create and update player shops without any issues but when I go to purchase an item from a shopkeeper that I just made the item goes into my inventory for a split second and then goes back to the shopkeeper. 

- I confirmed the chest as the required amount of items
- I confirmed the player has the correct item to purchase items in the chest
- I placed the chest in multiple locations with same result 
- Created shops with different items with the same result
- No errors appear in the console

I am currently running Shopkeepers 2.2.1 and the only other mod I am running is GriefPrevention 16.8 but the issue happens even with GriefPrevention disabled

**Comment by blablubbabc** [comment] 2018-07-17 16:38
* Make sure that you are not using any client mods, and that your client is using the latest 1.12.2 MC version as well.
* In case you are not using Spigot: Try if you can reproduce the issue on a fresh spigot server. (PaperMC for example has a few internal item related differences which might interfere here, for example related to enchantments).
* Make sure you are running the latest version of spigot 1.12.2: There has recently been at least one item related fix (involving the internal data of items that got repaired in an anvil).
* Turn on debug mode and try the trade again: This might print additional information into the console log.

Usually this type of issue is caused by there being a discrepancy between what the client sees the items to be, and what the invovled items actually are on the server. Any small, internal differences (like the order of the internal item data) might make a difference here.
So can you elaborate a bit more on what types of items you are having this issue with? How do you create those items?

Ideally I would need to be able to reproduce this on a fresh server, in order to be able to debug this.

**Comment by blablubbabc** [comment] 2018-08-16 19:25
Closing this as there has not been further information on how to reproduce this.

**Closed by blablubbabc** 2018-08-16 19:25 UTC
Labels: cannot-reproduce
