### ISSUE TITLE
Name Tag Color Not Holding

### ISSUE THREAD

**Issue by D1N60** [Shopkeepers/Shopkeepers#679] opened 2020-08-04 07:10 UTC
Shopkeepers version: 2.10.0
Spigot version: This server is running CraftBukkit version git-Spigot-6f4ff1b-983305b (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
Reproduction on a fresh and up-to-date Spigot server:

I was ABLE to reproduce my issue on a freshly setup and up-to-date Spigot server (currently This server is running CraftBukkit version git-Spigot-6f4ff1b-983305b (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)) with the latest version of Shopkeepers (currently 2.10.0), with no other plugins and with no kinds of other server or client mods.

The issue:
When changing the nametag color in the GUI. It often reverts back to green (&2 or maybe &a)
This has only been tested and has happened for admin-shops. Please advise.
Thanks!

**Comment by blablubbabc** [comment] 2020-08-04 15:20
Since you are not able to change the nametag color by default, I assume you have enabled color codes in the `name-regex` setting? Can you post your `name-regex` setting?

Regarding the green prefix: There are two prefixes, `nameplate-prefix` and `msg-trading-title-prefix`. These are always applied in front of the name. However, this should not affect the displayed color: If the name itself contains another color it will override the default prefix color.

I just tried this with an admin shop and was not able to reproduce this issue: http://prntscr.com/ttxd5j

**Comment by blablubbabc** [comment] 2020-08-13 04:28
Closing this as no further information was provided. If you figure out the cause or have further information which might help track down the cause of this issue, let me know.

**Closed by blablubbabc** 2020-08-13 04:28 UTC
Labels: cannot-reproduce, waiting
