### ISSUE TITLE
[Feature Request] GeyserMC Support (Bedrock Clients)

### ISSUE THREAD

**Issue by Matthew-MBG** [Shopkeepers/Shopkeepers#731] opened 2021-04-12 17:34 UTC
Lots of servers use the plugin "GeyserMC" allowing bedrock players to join, but apparently they can't open shopkeepers. (Tested on an Xbox One WITH op and perms). I would love to see support for this plugin, and it would really help my server!

**Comment by blablubbabc** [comment] 2021-04-12 17:37
Duplicate of: #730

**Closed by blablubbabc** 2021-04-12 17:37 UTC
