### ISSUE TITLE
World Guard Incompatibility 

### ISSUE THREAD

**Issue by soupcoup** [Shopkeepers/Shopkeepers#774] opened 2021-12-30 15:51 UTC
1.18.1 versions/actions are incompatible with world guard 1.18.1 snapshot after a few server restarts the villagers begin to not spawn in and i get this error in the console when i do /plugman reload shopkeepers with world guard on the server

[07:45:21 INFO]: [Shopkeepers] Loaded all plugin classes (335 ms).
[07:45:21 INFO]: [Shopkeepers] Loading config.
[07:45:21 INFO]: [Shopkeepers] Loading language file: language-en-default.yml
[07:45:21 INFO]: [Shopkeepers] Registering defaults.
[07:45:21 INFO]: [Shopkeepers] Enabling Shopkeepers v2.14.1-SNAPSHOT+52e83bb6
[07:45:21 INFO]: [Shopkeepers] Config already loaded.
[07:45:21 INFO]: [Shopkeepers] Language file already loaded.
[07:45:21 INFO]: [Shopkeepers] MC 1.16 exclusive features are enabled.
[07:45:21 INFO]: [Shopkeepers] MC 1.17 exclusive features are enabled.
[07:45:21 INFO]: [Shopkeepers] Spigot-based server found: Enabling Spigot exclusive features.
[07:45:21 INFO]: [Shopkeepers] Testing server assumptions ...
[07:45:21 INFO]: [Shopkeepers] Server assumption tests passed (3.93 ms).
[07:45:21 INFO]: [Shopkeepers] Defaults already registered.
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractEntityEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractAtEntityEvent' at priority LOWEST in front of an event handler of plugin Graves
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractAtEntityEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Citizen shops enabled, but Citizens plugin not found or disabled.
[07:45:24 INFO]: [Shopkeepers] Moving a handler for event 'AsyncPlayerChatEvent' at priority LOWEST in front of an event handler of plugin NexEngine
[07:45:24 ERROR]: Error occurred while enabling Shopkeepers v2.14.1-SNAPSHOT+52e83bb6 (Is it up to date?)
java.lang.IllegalStateException: This listener is already registered to priority LOWEST
        at org.bukkit.event.HandlerList.register(HandlerList.java:113) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:276) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:192) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:145) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.chatinput.ChatInput.onEnable(ChatInput.java:62) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:333) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManagMoving a handler for event 'PlayerInteractEntityEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractAtEntityEvent' at priority LOWEST in front of an event handler of plugin Graves
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractAtEntityEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Moving a handler for event 'PlayerInteractEvent' at priority LOWEST in front of an event handler of plugin GriefPrevention
[07:45:23 INFO]: [Shopkeepers] Citizen shops enabled, but Citizens plugin not found or disabled.
[07:45:24 INFO]: [Shopkeepers] Moving a handler for event 'AsyncPlayerChatEvent' at priority LOWEST in front of an event handler of plugin NexEngine
[07:45:24 ERROR]: Error occurred while enabling Shopkeepers v2.14.1-SNAPSHOT+52e83bb6 (Is it up to date?)
java.lang.IllegalStateException: This listener is already registered to priority LOWEST
        at org.bukkit.event.HandlerList.register(HandlerList.java:113) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:276) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:192) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.util.bukkit.EventUtils.enforceExecuteFirst(EventUtils.java:145) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.chatinput.ChatInput.onEnable(ChatInput.java:62) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at com.nisovin.shopkeepers.SKShopkeepersPlugin.onEnable(SKShopkeepersPlugin.java:333) ~[Shopkeepers-2.14.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugMan(1).jar:?]er.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:304) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:262) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:393) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[PlugMan(1).jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[PlugMan(1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:876) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2268) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2079) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2060) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1362) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1268) ~[paper-1.18.1.jar:git-Paper-79]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-79]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[07:45:24 INFO]: [Shopkeepers] Disabling Shopkeepers v2.14.1-SNAPSHOT+52e83bb6
[07:45:24 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.MinecraftServer.getCommandDispatcher()
[07:45:24 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.BukkitCommandWrap.wrap(BukkitCommandWrap.java:60)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.PluginUtil.lambda$load$4(PluginUtil.java:317)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[07:45:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:45:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:24 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.MinecraftServer.getCommandDispatcher()
[07:45:24 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.BukkitCommandWrap.wrap(BukkitCommandWrap.java:60)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.PluginUtil.lambda$load$4(PluginUtil.java:317)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[07:45:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:45:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:24 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.MinecraftServer.getCommandDispatcher()
[07:45:24 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.BukkitCommandWrap.wrap(BukkitCommandWrap.java:60)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.PluginUtil.lambda$load$4(PluginUtil.java:317)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[07:45:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:45:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[07:45:24 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.MinecraftServer.getCommandDispatcher()
[07:45:24 WARN]:        at java.base/java.lang.Class.getDeclaredMethod(Class.java:2675)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.BukkitCommandWrap.wrap(BukkitCommandWrap.java:60)
[07:45:24 WARN]:        at PlugMan(1).jar//com.rylinaux.plugman.util.PluginUtil.lambda$load$4(PluginUtil.java:317)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101)
[07:45:24 WARN]:        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1547)
[07:45:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1470)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1264)
[07:45:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
[07:45:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

I have shops enabled in my world guard flags and there is no other plugin that seems to be causing the issue.
the plugin works at first when i put in the 1.18 action version and then after 4 restarts stopped spawning villagers in
ive been replacing the versions with different ones and managing to get it to work for a few restarts but it always eventually breaks, what other info do you need from me to solve this issue

**Comment by blablubbabc** [comment] 2021-12-30 18:30
This issue is most likely caused by an incompatibility with one of your other plugins: My guess is that one of your other plugins is messing with internals of Bukkit's event system and has caused a bug by doing that.

Why do you think this issue is caused by WorldGuard?

Another user encounter the same error and it turned out that the issue was DiscordSRV: https://github.com/DiscordSRV/DiscordSRV/issues/1347
If you use DiscordSRV, then try a newer version (not sure if they have released the fix yet), disable all debugging features inside the config, and/or try to reproduce your issue without DiscordSRV running on the server.

If you are not using DiscordSRV, then you will need to do some further testing to figure out which other plugin is responsible for this plugin incompatibility (e.g. by trying to reproduce the issue with increasingly smaller sets of plugins running on the server until you identify the plugin responsible for this).

**Comment by soupcoup** [comment] 2021-12-30 20:11
there might be errors related to other plugins but i dont think those errors are actually causing anything. upon removing world guard from my server the shopkeepers are instantly able to spawn in ive had to temporarily remove it from my server and use an alternative in order to have the shopkeepers be present upon the server starting. any other incompatibility doesnt seem to actually prevent it from functioning but world guard.

**Comment by blablubbabc** [comment] 2021-12-31 00:50
My test server is running with WorldEdit and WorldGuard as well, and I cannot observe any issues there. I also looked into the Bukkit implementation of WorldEdit and WorldGuard but was not able to spot any oddities in how they interact with Bukkit's event system. So as it stands, I cannot reproduce any issues with Shopkeepers and WorldEdit+WorldGuard alone.

My guess is still that the actual issue is caused by one of your other plugins on the server.

**Comment by blablubbabc** [comment] 2022-01-05 09:35
Closing this as no further information has been provided that could help reproduce or pin-down the issue.

If you have further information, such as a list of other plugins running on your server, let me know. The plugin list should ideally be small enough to still reproduce the issue, but not too large so that it can be inspected without spending too much time and effort (I won't look through dozens of plugins to try to spot the cause of the issue; but a handful of plugins is fine).

**Closed by blablubbabc** 2022-01-05 09:35 UTC
Labels: cannot-reproduce, incompatibility

**Comment by blablubbabc** [comment] 2022-01-06 10:58
In the latest snapshot of Shopkeepers (https://github.com/Shopkeepers/Shopkeepers/suites/4849701550/artifacts/137679806), I have added some additional log output whenever one runs into this issue. This additional log output should make it easier to identify the plugin that is responsible for the issue.

However, if you decide to run this snapshot version of Shopkeepers, first make a backup of your current Shopkeepers data, because reverting from the snapshot back to the latest release version might not be supported and then require you to revert the Shopkeepers plugin data from the backup.

Let me know if this yields any useful information.
