### ISSUE TITLE
Impossible to make a certain trade

### ISSUE THREAD

**Issue by Wartets** [Shopkeepers/Shopkeepers#874] opened 2024-04-19 01:35 UTC
## Preliminaries:

* **Shopkeepers version:** `Shopkeepers-2.19.0`
* **Spigot version:** `PaperSpigot - 1.20.2 (Build 223)`
---

* I have checked that my issue/question does not get answered by:
  * The [documentation](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki).
  * The [FAQ](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Frequently-Asked-Questions).
  * The [Known Issues](https://github.com/Shopkeepers/Shopkeepers-Wiki/wiki/Known-Issues).
* I have checked all open and closed [issues](https://github.com/Shopkeepers/Shopkeepers/issues), but none seems to fit my issue/question.

## Reproduction on a fresh and up-to-date Spigot server:

I was **able** to reproduce my issue on a freshly set up and up-to-date Spigot server (currently **`PaperSpigot - 1.20.2 (Build 223)`**) with the latest version of Shopkeepers (currently **`Shopkeepers-2.19.0`**), with no other plugins and with no kinds of other server or client mods.

## The issue:

Provide a detailed description of the issue and information on how to reproduce it.

I wanted to add to the shop a way to buy a warden egg that spawns an illusionist, in exchange for a bottle of xp and an allay egg. It worked perfectly, and on my server the shopkeeper never had a problem. Then one day the shopkeeper stopped loading. I don't know what to do, especially since I liked this trade.
If I manually remove the trade from the save.ylm file, shopkeeper works again.

Here's the log: https://haste.zendrique.fr/kifidanodu.sql

And here is the part of the shopkeeper file for the trade: https://haste.zendrique.fr/acetorepun.yaml

Hopefully you can fix this bug, best regards

(great plugin by the way)

**Comment by blablubbabc** [comment] 2024-04-19 21:44
Duplicate of https://github.com/Shopkeepers/Shopkeepers/issues/718

This is an upstream issue (see attached Spigot issue): Spigot's item serialization (which is what the Shopkeepers plugin uses to save and load items to file) does not support spawn eggs with entity data of another mob type.

**Closed by blablubbabc** 2024-04-19 21:44 UTC
