### ISSUE TITLE
Bug inventory

### ISSUE THREAD

**Issue by CarpeDiemYT** [Shopkeepers/Shopkeepers#702] opened 2020-10-18 16:42 UTC
Hello very good, I have a pretty strange bug and I don't know how to fix it I give them a video so they can understand me easier

[https://drive.google.com/file/d/1kbN_1Sn56SxpZ2SqjHrLurb6Ix8DzoPn/view?usp=sharing](url)

**Comment by blablubbabc** [comment] 2020-10-21 19:33
* Are both of those shopkeepers? If yes, what is the difference between them? Maybe some other plugin is blocking the inventory opening or trading due to some constraint, eg. affecting the region?
* Can you try to make this a minimal and reproduciable description of what I need to do to reproduce this? I.e. remove other plugins, make sure you are using up-to-date Spigot, no client mods, etc. If the issue goes away by one of these steps, then investigate there.
* My current guess is that it's probably some plugin incompatibility.

**Comment by blablubbabc** [comment] 2020-12-28 08:14
Closing this as no further information was provided. My guess is still that some other plugin might be involved here.

**Closed by blablubbabc** 2020-12-28 08:14 UTC
Labels: waiting
