### ISSUE TITLE
1.14.1 Shopkeepers few minor issues

### ISSUE THREAD

**Issue by hurrgurl** [Shopkeepers/Shopkeepers#564] opened 2019-05-15 20:32 UTC
Using Shopkeepers-2.7.0-20190508.225429-1.jar and Paper 21
https://papermc.io/ci/job/Paper-1.14/

If paper.yml has
keep-spawn-loaded: true
keep-spawn-loaded-range: 10

Shopkeepers will duplicate infinitely (becoming normal villagers) if outside of spawn loaded range. 
Have yet to figure out what causes it, likely has something to do with chunk load/unload.

Additionally, turning off gravity in shopkeepers config file still makes them fall down for me.

This did not occur in 1.13 shopkeepers.

P.S.
All shopkeepers saves/configs have been updated to 1.14.1 paper without any issues.

**Comment by blablubbabc** [comment] 2019-05-15 21:05
Can you please try to reproduce your issues on the latest version of Spigot? Paper has additional changes on top which I am not familar with, so I can't help you if this is paper-specific / it would take me additional time to find out which paper-specific changes are causing this, in case this does not also happen on Spigot.

**Comment by blablubbabc** [comment] 2019-05-27 18:11
Closing this as duplicate since https://github.com/Shopkeepers/Shopkeepers/issues/562 is already concerned with issues regarding running Shopkeepers on 1.14.x

**Closed by blablubbabc** 2019-05-27 18:11 UTC
